// packages/slider/src/angular/slider/shared.ts
// Slider, the Angular lifecycle half. The logic (value/limit/disabled folds, the step-option
// layout) and the native render live in @symbiotejs/slider core, shared verbatim with the Vue
// adapter; here Angular supplies plain class fields (mirroring ActivityIndicatorBase/SwitchBase)
// plus real @Output() EventEmitters for the four native callbacks, and renders through
// DescriptorOutlet — the generic descriptorToAngular bridge (angular-adapter skill §6) — since
// this component has no imperative-ref need the Descriptor prop bag can't carry. The native
// RNCSlider view carries no symbiote metadata: the engine derives its events and color
// processors from the library's ViewConfig at runtime, registered by the side-effect import in
// ../../register (pulled in by the package barrel, NOT here, so this module and its tests stay
// free of the third-party spec). See CLAUDE.md <third_party_rn_packages_are_react_only> and
// ADR 0027.
//
// KNOWN GAP (deliberate, scoped by the task this module was built for): the custom `StepMarker`
// render slot (a per-adapter overlay element — a React FC, a Vue scoped slot) has no Angular
// equivalent yet. The natural analogue is a `@ContentChild(TemplateRef) stepMarker?:
// TemplateRef<IStepMarkerProps>` projected per step cell via `NgTemplateOutlet`, but wiring an
// embedded view per cell (constructing it, feeding its context, keeping it in step with
// DescriptorOutlet's imperative patch model, which has no notion of TemplateRefs) is
// disproportionate complexity for a path no real caller exercises today (examples/react/App.tsx's
// Slider usage has no step markers at all). Everything else — value/limits/disabled/colors/
// thumbImage/style/every event, and the DEFAULT numbered step indicator (`renderStepNumber`) — is
// fully implemented below; only the custom-marker overlay is unimplemented.

import {
  ChangeDetectorRef,
  Directive,
  ElementRef,
  EventEmitter,
  inject,
  Input,
  Output,
  type OnChanges,
} from '@angular/core';
import { anchorHostStyle } from '@symbiotejs/angular';
import { resolveAccessibilityProps } from '@symbiotejs/components';
import type {
  IAccessibilityProps,
  IAccessibilityStateValue,
  IAriaProps,
  IDescriptor,
} from '@symbiotejs/components';
import { dlog, type ISymbioteEvent } from '@symbiotejs/engine';
import {
  sanitizeSliderValue,
  resolveSliderDisabled,
  resolveSliderAccessibilityState,
  resolveSliderLowerLimit,
  resolveSliderUpperLimit,
  valueFromSliderEvent,
  shouldRenderStepsIndicator,
  resolveThumbTintColor,
  shouldPassNativeThumbImage,
  isInvalidLimitConfig,
  computeStepOptions,
  renderSlider,
  renderStepsIndicator,
  SLIDER_DEFAULT_MINIMUM_VALUE,
  SLIDER_DEFAULT_MAXIMUM_VALUE,
  SLIDER_DEFAULT_STEP,
  SLIDER_ON_CHANGE,
  SLIDER_ON_VALUE_CHANGE,
  SLIDER_ON_SLIDING_START,
  SLIDER_ON_SLIDING_COMPLETE,
  SLIDER_ON_ACCESSIBILITY_ACTION,
  type ISliderPlatform,
  type ISliderProps as ISliderBaseProps,
  type ISliderViewProps,
} from '../../core';

export type ISliderProps = Omit<
  ISliderBaseProps,
  'onValueChange' | 'onSlidingStart' | 'onSlidingComplete' | 'onAccessibilityAction'
>;

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

// Narrows anchorHostStyle's `unknown` (it reads an opaque engine prop bag) to the shape
// ISliderProps['style'] actually declares — the same runtime guard the Angular adapter's
// ActivityIndicator uses for the identical reason: a style value is structurally opaque at the
// type level, so this only rules out non-objects, never validates individual style keys.
function asStyle(value: unknown): ISliderProps['style'] {
  return typeof value === 'object' && value !== null ? value : undefined;
}

@Directive()
export abstract class SliderBase implements ISliderProps, OnChanges {
  @Input() value?: number;
  @Input() minimumValue?: number;
  @Input() maximumValue?: number;
  @Input() step?: number;
  @Input() lowerLimit?: number;
  @Input() upperLimit?: number;
  @Input() minimumTrackTintColor?: ISliderProps['minimumTrackTintColor'];
  @Input() maximumTrackTintColor?: ISliderProps['maximumTrackTintColor'];
  @Input() thumbTintColor?: ISliderProps['thumbTintColor'];
  @Input() disabled?: boolean;
  @Input() inverted?: boolean;
  @Input() tapToSeek?: boolean;
  @Input() vertical?: boolean;
  @Input() thumbImage?: ISliderProps['thumbImage'];
  @Input() minimumTrackImage?: ISliderProps['minimumTrackImage'];
  @Input() maximumTrackImage?: ISliderProps['maximumTrackImage'];
  @Input() trackImage?: ISliderProps['trackImage'];
  @Input() thumbSize?: number;
  @Input() accessibilityUnits?: string;
  @Input() accessibilityIncrements?: readonly string[];
  @Input() renderStepNumber?: boolean;
  @Input() testID?: string;
  @Input() style?: ISliderProps['style'];

  @Input() nativeID?: string;
  @Input() accessible?: boolean;
  @Input() accessibilityLabel?: string;
  @Input() accessibilityHint?: string;
  @Input() accessibilityRole?: IAccessibilityProps['accessibilityRole'];
  @Input() accessibilityState?: IAccessibilityStateValue;
  @Input() accessibilityValue?: IAccessibilityProps['accessibilityValue'];
  @Input() accessibilityActions?: IAccessibilityProps['accessibilityActions'];
  @Input() accessibilityLabelledBy?: string | string[];
  @Input() importantForAccessibility?: IAccessibilityProps['importantForAccessibility'];
  @Input() accessibilityLiveRegion?: IAccessibilityProps['accessibilityLiveRegion'];
  @Input() screenReaderFocusable?: boolean;
  @Input() accessibilityViewIsModal?: boolean;
  @Input() accessibilityElementsHidden?: boolean;
  @Input() accessibilityIgnoresInvertColors?: boolean;
  @Input() accessibilityLanguage?: string;
  @Input() accessibilityRespondsToUserInteraction?: boolean;
  @Input() accessibilityShowsLargeContentViewer?: boolean;
  @Input() accessibilityLargeContentTitle?: string;
  @Input() onAccessibilityTap?: (event: ISymbioteEvent) => void;
  @Input() onMagicTap?: (event: ISymbioteEvent) => void;
  @Input() onAccessibilityEscape?: (event: ISymbioteEvent) => void;

  @Input() role?: IAriaProps['role'];
  @Input('aria-label') ariaLabel?: string;
  @Input('aria-labelledby') ariaLabelledBy?: string;
  @Input('aria-live') ariaLive?: IAriaProps['aria-live'];
  @Input('aria-hidden') ariaHidden?: boolean;
  @Input('aria-busy') ariaBusy?: boolean;
  @Input('aria-checked') ariaChecked?: boolean | 'mixed';
  @Input('aria-disabled') ariaDisabled?: boolean;
  @Input('aria-expanded') ariaExpanded?: boolean;
  @Input('aria-selected') ariaSelected?: boolean;
  @Input('aria-modal') ariaModal?: boolean;
  @Input('aria-valuemax') ariaValueMax?: number;
  @Input('aria-valuemin') ariaValueMin?: number;
  @Input('aria-valuenow') ariaValueNow?: number;
  @Input('aria-valuetext') ariaValueText?: string;

  // The four native callbacks, as real EventEmitters — no v-model-style two-way twin (that was
  // Vue-specific v-model sugar; Angular has no equivalent concept here).
  @Output() readonly valueChange = new EventEmitter<number>();
  @Output() readonly slidingStart = new EventEmitter<number>();
  @Output() readonly slidingComplete = new EventEmitter<number>();
  @Output() readonly accessibilityAction = new EventEmitter<ISymbioteEvent>();

  protected abstract readonly platform: ISliderPlatform;

  private readonly changeDetector = inject(ChangeDetectorRef);
  // This component's OWN host — the non-painting anchor `class="..."` at the use site resolves
  // onto (see anchorHostStyle's doc comment, @symbiotejs/angular) — NOT the descriptor-outlet-
  // rendered wrapper the `descriptor` getter below builds. Merged FIRST so an explicit `style`
  // @Input still wins (flattenStyle's later-wins collapse), mirroring every other composed
  // component's anchor merge.
  private readonly elementRef = inject(ElementRef);

  // The value native last reported, kept only to mark the active step in the indicator. Not the
  // controlled value — the slider is uncontrolled during a drag (no snap-back), mirroring the
  // Vue lifecycle's `reportedValue` ref.
  private reportedValue: number | undefined;
  // The measured wrapper width the step indicator lays out against; 0 until the first layout.
  private width = 0;

  ngOnChanges(): void {
    // No fold needed here: `descriptor` is a getter re-evaluated on every OnPush check the
    // template's `[node]="descriptor"` binding triggers, so an @Input change already recomputes
    // the render on its own. OnChanges exists so this class satisfies the same lifecycle contract
    // as the rest of the input-driven components in this adapter.
  }

  protected readonly handleValueChange = (event: ISymbioteEvent): void => {
    const value = valueFromSliderEvent(event);
    if (value === undefined) return;
    this.reportedValue = value;
    this.valueChange.emit(value);
  };

  protected readonly handleSlidingStart = (event: ISymbioteEvent): void => {
    const value = valueFromSliderEvent(event);
    if (value !== undefined) this.slidingStart.emit(value);
  };

  protected readonly handleSlidingComplete = (event: ISymbioteEvent): void => {
    const value = valueFromSliderEvent(event);
    if (value !== undefined) this.slidingComplete.emit(value);
  };

  protected readonly handleAccessibilityAction = (event: ISymbioteEvent): void => {
    this.accessibilityAction.emit(event);
  };

  // Native onLayout fires through the engine's event dispatch (Renderer2.listen), OUTSIDE
  // Angular's zoneless change-detection notification — the same async-commit-timing shape the
  // angular-adapter skill (§5) documents and the sticky-header component already works around
  // (`ChangeDetectorRef.markForCheck()`). Mutating `width` alone would never repaint the step
  // indicator, since nothing would tell the OnPush view it is dirty.
  protected readonly handleLayout = (event: ISymbioteEvent): void => {
    const layout = event.nativeEvent.layout;
    if (isRecord(layout) && typeof layout.width === 'number') {
      this.width = layout.width;
      this.changeDetector.markForCheck();
    }
  };

  private inputProps(): ISliderProps {
    return {
      value: this.value,
      minimumValue: this.minimumValue,
      maximumValue: this.maximumValue,
      step: this.step,
      lowerLimit: this.lowerLimit,
      upperLimit: this.upperLimit,
      minimumTrackTintColor: this.minimumTrackTintColor,
      maximumTrackTintColor: this.maximumTrackTintColor,
      thumbTintColor: this.thumbTintColor,
      disabled: this.disabled,
      inverted: this.inverted,
      tapToSeek: this.tapToSeek,
      vertical: this.vertical,
      thumbImage: this.thumbImage,
      minimumTrackImage: this.minimumTrackImage,
      maximumTrackImage: this.maximumTrackImage,
      trackImage: this.trackImage,
      thumbSize: this.thumbSize,
      accessibilityUnits: this.accessibilityUnits,
      accessibilityIncrements: this.accessibilityIncrements,
      renderStepNumber: this.renderStepNumber,
      testID: this.testID,
      style: [asStyle(anchorHostStyle(this.elementRef)), this.style],
      nativeID: this.nativeID,
      accessible: this.accessible,
      accessibilityLabel: this.accessibilityLabel,
      accessibilityHint: this.accessibilityHint,
      accessibilityRole: this.accessibilityRole,
      accessibilityState: this.accessibilityState,
      accessibilityValue: this.accessibilityValue,
      accessibilityActions: this.accessibilityActions,
      accessibilityLabelledBy: this.accessibilityLabelledBy,
      importantForAccessibility: this.importantForAccessibility,
      accessibilityLiveRegion: this.accessibilityLiveRegion,
      screenReaderFocusable: this.screenReaderFocusable,
      accessibilityViewIsModal: this.accessibilityViewIsModal,
      accessibilityElementsHidden: this.accessibilityElementsHidden,
      accessibilityIgnoresInvertColors: this.accessibilityIgnoresInvertColors,
      accessibilityLanguage: this.accessibilityLanguage,
      accessibilityRespondsToUserInteraction: this.accessibilityRespondsToUserInteraction,
      accessibilityShowsLargeContentViewer: this.accessibilityShowsLargeContentViewer,
      accessibilityLargeContentTitle: this.accessibilityLargeContentTitle,
      onAccessibilityTap: this.onAccessibilityTap,
      onMagicTap: this.onMagicTap,
      onAccessibilityEscape: this.onAccessibilityEscape,
      role: this.role,
      'aria-label': this.ariaLabel,
      'aria-labelledby': this.ariaLabelledBy,
      'aria-live': this.ariaLive,
      'aria-hidden': this.ariaHidden,
      'aria-busy': this.ariaBusy,
      'aria-checked': this.ariaChecked,
      'aria-disabled': this.ariaDisabled,
      'aria-expanded': this.ariaExpanded,
      'aria-selected': this.ariaSelected,
      'aria-modal': this.ariaModal,
      'aria-valuemax': this.ariaValueMax,
      'aria-valuemin': this.ariaValueMin,
      'aria-valuenow': this.ariaValueNow,
      'aria-valuetext': this.ariaValueText,
    };
  }

  get descriptor(): IDescriptor {
    const props = resolveAccessibilityProps<ISliderProps>(this.inputProps());
    const {
      value,
      minimumValue: minimumValueInput,
      maximumValue: maximumValueInput,
      step: stepInput,
      lowerLimit: lowerLimitInput,
      upperLimit: upperLimitInput,
      disabled,
      inverted: invertedInput,
      thumbTintColor,
      thumbImage,
      accessibilityState,
      renderStepNumber,
      style,
      ...passthrough
    } = props;

    const minimumValue = minimumValueInput ?? SLIDER_DEFAULT_MINIMUM_VALUE;
    const maximumValue = maximumValueInput ?? SLIDER_DEFAULT_MAXIMUM_VALUE;
    const step = stepInput ?? SLIDER_DEFAULT_STEP;
    const lowerLimit = resolveSliderLowerLimit(lowerLimitInput);
    const upperLimit = resolveSliderUpperLimit(upperLimitInput);
    if (isInvalidLimitConfig(lowerLimit, upperLimit)) {
      dlog('Slider: lowerLimit must be smaller than upperLimit');
    }
    const inverted = invertedInput ?? false;
    const hasThumbImage = thumbImage !== undefined;
    // No custom-StepMarker slot on Angular yet (see the module doc comment above) — showSteps
    // only ever considers renderStepNumber.
    const showSteps = shouldRenderStepsIndicator(false, renderStepNumber);
    const nativeThumbImage = shouldPassNativeThumbImage(false, hasThumbImage)
      ? thumbImage
      : undefined;

    const view: ISliderViewProps = {
      value: sanitizeSliderValue(value),
      minimumValue,
      maximumValue,
      step,
      lowerLimit,
      upperLimit,
      disabled: resolveSliderDisabled(disabled, accessibilityState),
      inverted,
      thumbTintColor: resolveThumbTintColor(thumbTintColor, false, hasThumbImage),
      thumbImage: nativeThumbImage,
      accessibilityState: resolveSliderAccessibilityState(disabled, accessibilityState),
      width: this.width,
      style,
      passthrough: {
        ...passthrough,
        [SLIDER_ON_CHANGE]: this.handleValueChange,
        [SLIDER_ON_VALUE_CHANGE]: this.handleValueChange,
        [SLIDER_ON_SLIDING_START]: this.handleSlidingStart,
        [SLIDER_ON_SLIDING_COMPLETE]: this.handleSlidingComplete,
        [SLIDER_ON_ACCESSIBILITY_ACTION]: this.handleAccessibilityAction,
      },
    };

    if (!showSteps) {
      return renderSlider(view, this.platform, { onLayout: this.handleLayout });
    }

    const options = computeStepOptions(
      minimumValue,
      maximumValue,
      step,
      this.platform.stepResolution,
    );
    const currentValue = this.reportedValue ?? view.value ?? minimumValue;
    const steps = renderStepsIndicator({
      options,
      currentValue,
      width: this.width,
      renderStepNumber: renderStepNumber === true,
      thumbImage,
      inverted,
      platform: this.platform,
    });
    return renderSlider(view, this.platform, { steps, onLayout: this.handleLayout });
  }
}

// packages/slider/src/react/slider/shared.ts
// Slider, the React lifecycle half. The logic (value/limit/disabled folds, the step-option layout)
// and the native render live in @symbiotejs/slider core, shared verbatim with the Vue adapter; here
// React supplies the lifecycle — useState for the last-reported value (to mark the active step)
// and the measured width (for the step indicator), useEffect for the limit warning — plus the
// descriptor bridge and forwardRef to the native view (matching the library's forwardRef). The
// native RNCSlider carries no symbiote metadata: the engine derives its events and color/image
// processors from the library's ViewConfig, registered by ../register (the package barrel pulls
// it). This is the React twin of the Vue wrapper; both drive the engine, NEITHER imports the
// library's React Slider component. See CLAUDE.md <third_party_rn_packages_are_react_only>, ADR 0027.

import { createElement, forwardRef, useCallback, useEffect, useState } from 'react';
import type {
  FC,
  ForwardRefExoticComponent,
  PropsWithoutRef,
  ReactElement,
  RefAttributes,
} from 'react';
import { descriptorToReact, Image } from '@symbiotejs/react';
import { resolveAccessibilityProps } from '@symbiotejs/components';
import type { IDescriptor, IDescriptorChild, IImageSourceProp } from '@symbiotejs/components';
import { dlog, type ISymbioteEvent, type ISymbioteNode } from '@symbiotejs/engine';
import {
  sanitizeSliderValue,
  resolveSliderDisabled,
  resolveSliderAccessibilityState,
  resolveSliderLowerLimit,
  resolveSliderUpperLimit,
  valueFromSliderEvent,
  shouldRenderStepsIndicator,
  resolveThumbTintColor,
  shouldPassNativeThumbImage,
  isInvalidLimitConfig,
  computeStepOptions,
  orderStepOptions,
  stepNumberFontSize,
  renderSlider,
  renderSliderNative,
  resolveStepsContainerStyle,
  renderStepsIndicator,
  STEP_INDICATOR_ELEMENT_STYLE,
  TRACK_MARK_CONTAINER_STYLE,
  THUMB_IMAGE_CONTAINER_STYLE,
  THUMB_IMAGE_STYLE,
  STEP_NUMBER_CONTAINER_STYLE,
  SLIDER_DEFAULT_MINIMUM_VALUE,
  SLIDER_DEFAULT_MAXIMUM_VALUE,
  SLIDER_DEFAULT_STEP,
  SLIDER_ON_CHANGE,
  SLIDER_ON_VALUE_CHANGE,
  SLIDER_ON_SLIDING_START,
  SLIDER_ON_SLIDING_COMPLETE,
  SLIDER_ON_ACCESSIBILITY_ACTION,
  type ISliderPlatform,
  type ISliderProps as ISliderBaseProps,
  type ISliderViewProps,
  type IStepMarkerProps,
} from '../../core';

// React's flavored prop type: the agnostic base plus the per-adapter StepMarker — a render
// component returning a React element, which (per CLAUDE.md <prop_types_split_agnostic_vs_per_adapter>)
// cannot live in the shared layer. Same name as the agnostic base by the split convention (cf.
// IPressableProps declared per-adapter); Vue takes the same marker as a `#stepMarker` scoped slot.
export interface ISliderProps extends ISliderBaseProps {
  StepMarker?: FC<IStepMarkerProps>;
  // Forwarded onto the OUTER wrapper View, like `style` (resolveSliderWrapperStyle) — resolves
  // through the shared style registry. Explicitly destructured below, not left in `...passthrough`,
  // which lands on the INNER native RNCSlider leaf (renderSliderNative) — the same wrapper/inner
  // routing bug ImageBackground was fixed for.
  className?: string;
}

type ISliderComponent = ForwardRefExoticComponent<
  PropsWithoutRef<ISliderProps> & RefAttributes<ISymbioteNode>
>;

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function toChild(child: IDescriptorChild): ReactElement | string {
  return typeof child === 'string' ? child : descriptorToReact(child);
}

// renderSlider's Descriptor IS the outer wrapper (symbiote-view hosting the native leaf +
// optional steps overlay); className is reapplied on it here, exactly like ImageBackground's
// wrapper.
function withClassName(descriptor: IDescriptor, className: string | undefined): ReactElement {
  return createElement(
    descriptor.type,
    { key: descriptor.key, ...descriptor.props, className },
    ...descriptor.children.map(toChild),
  );
}

export function createSlider(platform: ISliderPlatform): ISliderComponent {
  return forwardRef<ISymbioteNode, ISliderProps>((rawProps, forwardedRef) => {
    // Slider owns its host wrapper rather than rendering through a symbiote View, so it folds
    // aria/role into accessibility* here; the rest (testID, accessibilityLabel, accessibility-
    // Actions, …) rides to the native node via `passthrough`.
    const props = resolveAccessibilityProps(rawProps);
    const {
      value,
      minimumValue,
      maximumValue,
      step,
      lowerLimit,
      upperLimit,
      disabled,
      inverted,
      thumbTintColor,
      thumbImage,
      accessibilityState,
      renderStepNumber,
      style,
      className,
      StepMarker,
      onValueChange,
      onSlidingStart,
      onSlidingComplete,
      onAccessibilityAction,
      ...passthrough
    } = props;

    const [reportedValue, setReportedValue] = useState<number | undefined>(undefined);
    const [width, setWidth] = useState(0);

    const handleValueChange = useCallback(
      (event: ISymbioteEvent): void => {
        const next = valueFromSliderEvent(event);
        if (next === undefined) return;
        setReportedValue(next);
        onValueChange?.(next);
      },
      [onValueChange],
    );
    const handleSlidingStart = useCallback(
      (event: ISymbioteEvent): void => {
        const next = valueFromSliderEvent(event);
        if (next !== undefined) onSlidingStart?.(next);
      },
      [onSlidingStart],
    );
    const handleSlidingComplete = useCallback(
      (event: ISymbioteEvent): void => {
        const next = valueFromSliderEvent(event);
        if (next !== undefined) onSlidingComplete?.(next);
      },
      [onSlidingComplete],
    );
    const handleAccessibilityAction = useCallback(
      (event: ISymbioteEvent): void => {
        onAccessibilityAction?.(event);
      },
      [onAccessibilityAction],
    );
    const handleLayout = useCallback((event: ISymbioteEvent): void => {
      const layout = event.nativeEvent.layout;
      if (isRecord(layout) && typeof layout.width === 'number') setWidth(layout.width);
    }, []);

    const minimum = minimumValue ?? SLIDER_DEFAULT_MINIMUM_VALUE;
    const maximum = maximumValue ?? SLIDER_DEFAULT_MAXIMUM_VALUE;
    const stepValue = step ?? SLIDER_DEFAULT_STEP;
    const lower = resolveSliderLowerLimit(lowerLimit);
    const upper = resolveSliderUpperLimit(upperLimit);

    useEffect(() => {
      if (isInvalidLimitConfig(lower, upper))
        dlog('Slider: lowerLimit must be smaller than upperLimit');
    }, [lower, upper]);

    const hasStepMarker = StepMarker !== undefined;
    const hasThumbImage = thumbImage !== undefined;
    const showSteps = shouldRenderStepsIndicator(hasStepMarker, renderStepNumber);
    // Passed to the native view raw — the engine runs the image processor derived from RNCSlider's
    // ViewConfig — and only when no custom marker draws its own thumb (matches the library).
    const nativeThumbImage = shouldPassNativeThumbImage(hasStepMarker, hasThumbImage)
      ? thumbImage
      : undefined;

    const view: ISliderViewProps = {
      value: sanitizeSliderValue(value),
      minimumValue: minimum,
      maximumValue: maximum,
      step: stepValue,
      lowerLimit: lower,
      upperLimit: upper,
      disabled: resolveSliderDisabled(disabled, accessibilityState),
      inverted: inverted ?? false,
      thumbTintColor: resolveThumbTintColor(thumbTintColor, hasStepMarker, hasThumbImage),
      thumbImage: nativeThumbImage,
      accessibilityState: resolveSliderAccessibilityState(disabled, accessibilityState),
      width,
      style,
      passthrough: {
        ...passthrough,
        ref: forwardedRef,
        [SLIDER_ON_CHANGE]: handleValueChange,
        [SLIDER_ON_VALUE_CHANGE]: handleValueChange,
        [SLIDER_ON_SLIDING_START]: handleSlidingStart,
        [SLIDER_ON_SLIDING_COMPLETE]: handleSlidingComplete,
        [SLIDER_ON_ACCESSIBILITY_ACTION]: handleAccessibilityAction,
      },
    };

    if (!showSteps) {
      return withClassName(renderSlider(view, platform, { onLayout: handleLayout }), className);
    }

    const options = computeStepOptions(minimum, maximum, stepValue, platform.stepResolution);
    const currentValue = reportedValue ?? view.value ?? minimum;

    if (StepMarker !== undefined) {
      const overlay = renderCustomStepsOverlay({
        options,
        currentValue,
        inverted: view.inverted,
        renderStepNumber: renderStepNumber === true,
        thumbImage,
        width,
        platform,
        StepMarker,
      });
      return createElement(
        'symbiote-view',
        { style: resolveStepsWrapperStyle(style, platform), onLayout: handleLayout, className },
        overlay,
        descriptorToReact(renderSliderNative(view, platform)),
      );
    }

    const steps = renderStepsIndicator({
      options,
      currentValue,
      width,
      renderStepNumber: renderStepNumber === true,
      thumbImage,
      inverted: view.inverted,
      platform,
    });
    return withClassName(
      renderSlider(view, platform, { steps, onLayout: handleLayout }),
      className,
    );
  });
}

// The wrapper style for the custom-marker steps path mirrors renderSlider's wrapper.
function resolveStepsWrapperStyle(style: unknown, platform: ISliderPlatform): unknown {
  return [platform.defaultStyle, style, { justifyContent: 'center' }];
}

type ICustomStepsParams = {
  options: readonly number[];
  currentValue: number;
  inverted: boolean;
  renderStepNumber: boolean;
  thumbImage: IImageSourceProp | undefined;
  width: number;
  platform: ISliderPlatform;
  StepMarker: FC<IStepMarkerProps>;
};

// The custom-marker overlay: the same flex row as the agnostic default, each mark hosting the
// user's StepMarker element (plus the thumbImage on the current step and the optional step
// number), mirroring the library's SliderTrackMark composition.
function renderCustomStepsOverlay(params: ICustomStepsParams): ReactElement {
  const fontSize = stepNumberFontSize(params.options.length);
  const ordered = orderStepOptions(params.options, params.inverted);
  const min = params.options[0];
  const max = params.options[params.options.length - 1];
  const cells = ordered.map((value, index) => {
    const trackChildren: ReactElement[] = [
      createElement(params.StepMarker, {
        key: 'marker',
        stepMarked: value === params.currentValue,
        currentValue: params.currentValue,
        index,
        min,
        max,
      }),
    ];
    if (params.thumbImage !== undefined && value === params.currentValue) {
      trackChildren.push(
        createElement(
          'symbiote-view',
          {
            key: 'thumb',
            style: THUMB_IMAGE_CONTAINER_STYLE,
            testID: 'sliderTrackMark-thumbImage',
          },
          createElement(Image, { source: params.thumbImage, style: THUMB_IMAGE_STYLE }),
        ),
      );
    }
    const cellChildren: ReactElement[] = [
      createElement(
        'symbiote-view',
        { key: 'track', style: TRACK_MARK_CONTAINER_STYLE },
        ...trackChildren,
      ),
    ];
    if (params.renderStepNumber) {
      cellChildren.push(
        createElement(
          'symbiote-view',
          { key: 'number', style: STEP_NUMBER_CONTAINER_STYLE },
          createElement(
            'symbiote-text',
            { testID: `${index}th-step`, style: { fontSize } },
            String(value),
          ),
        ),
      );
    }
    return createElement(
      'symbiote-view',
      { key: index, style: STEP_INDICATOR_ELEMENT_STYLE },
      ...cellChildren,
    );
  });
  return createElement(
    'symbiote-view',
    {
      pointerEvents: 'none',
      testID: 'StepsIndicator-Container',
      style: resolveStepsContainerStyle(params.width, params.platform),
    },
    ...cells,
  );
}
