// adapters/angular/src/components/scroll-view/sticky-header.ts
// Sticky headers: the Angular twin of adapters/{react,vue}/src/components/scroll-view/
// sticky-header.{tsx,ts}, the JS layer RN implements in ScrollView.js / ScrollViewStickyHeader.js.
//
// Source-based: RN does stickiness PURELY IN JS. A single `_scrollAnimatedValue` an Animated.event
// drives from `onScroll` feeds each flagged header's translateY through an interpolation that pins
// it to the top (or bottom, inverted) until the next header collides with it. The native Fabric
// scroll view does NOT honor `stickyHeaderIndices` on its own. The load-bearing top/inverted
// interpolation math (computeStickyInterpolation) lives framework-agnostic in @symbiote-native/components
// this file holds the Angular component shell, the layout state, and the interpolation
// build, sharing the math verbatim with React/Vue. Angular supplies only the lifecycle (inputs +
// manual change detection instead of useState/useEffect or refs/watch).
//
// This is the public sticky-header WRAPPER for explicit composition. ScrollView also auto-wraps
// projected direct children named by stickyHeaderIndices through its projection bridge (see
// projection.ts), because Angular templates cannot map <ng-content> children directly; that auto
// path intentionally uses this built-in wrapper rather than dynamically instantiating arbitrary
// custom component classes.

import {
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  Component,
  ElementRef,
  EventEmitter,
  Input,
  Output,
  inject,
  type OnChanges,
  type OnDestroy,
  type OnInit,
} from '@angular/core';
import {
  type AnimatedInterpolation,
  AnimatedValue,
  Platform,
  dlog,
  type ISymbioteEvent,
} from '@symbiote-native/engine';
import {
  createInitialStickyState,
  readLayoutNumber,
  reduceSticky,
  STICKY_HEADER_Z_INDEX,
  type IStickyAction,
  type IStickyEffect,
  type IStickyHeaderProps,
  type IStickyReducerInputs,
} from '@symbiote-native/components';
import { AnimatedView } from '../../modules/animated';
import { anchorHostStyle } from '../../primitives';

// A custom sticky wrapper must accept the same shape the built-in does: the IStickyHeaderProps
// fields as inputs + the wrapped child via <ng-content>. Unlike React/Vue, Angular ScrollView cannot
// AOT-safely instantiate an arbitrary component Type while auto-projecting stickyHeaderIndices,
// because that renderer-level bridge only sees committed engine nodes, not a ViewContainerRef with
// Angular projectable nodes. This type remains public for explicit composition: compose your wrapper
// around <ScrollViewStickyHeader>/<symbiote-sticky-header> in the template when custom visuals are
// needed. Auto projection intentionally uses the built-in wrapper.
export type IStickyHeaderComponentType = unknown;

// One sticky header. Measures its own y/height via onLayout, interpolates the shared scroll offset
// into a translateY that keeps it pinned to the top (or bottom, inverted) until the next header
// collides with it, and drives that translate through the native driver when available so the pin
// tracks scroll on the UI thread (no JS jitter). Ported from ScrollViewStickyHeader.js, including
// the Fabric ShadowTree debounce path. The inputs (scrollAnimatedValue/nextHeaderLayoutY/…) never
// reach the host node: they configure the interpolation; only the resolved transform reaches
// AnimatedView (a scrollAnimatedValue on a host node would crash Android's folly::dynamic).
@Component({
  selector: 'ScrollViewStickyHeader, symbiote-sticky-header',
  standalone: true,
  imports: [AnimatedView],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <AnimatedView
      [style]="headerStyle"
      [animatedProps]="headerAnimatedProps"
      [passthroughAnimatedPropExplicitValues]="passthrough"
    >
      <ng-content></ng-content>
    </AnimatedView>
  `,
})
export class ScrollViewStickyHeader
  implements Omit<IStickyHeaderProps, 'onLayout'>, OnInit, OnChanges, OnDestroy
{
  // A fresh fallback AnimatedValue keeps the component working if the parent ever fails to supply
  // one (the wrap invariant); held by IDENTITY in a plain field (Angular does not proxy fields).
  @Input() scrollAnimatedValue: AnimatedValue = new AnimatedValue(0);
  @Input() nextHeaderLayoutY: number | undefined = undefined;
  @Input() inverted: boolean | undefined = undefined;
  @Input() scrollViewHeight: number | undefined = undefined;
  // The parent's layout recorder (RN _onStickyHeaderLayout): records this header's own y so the
  // previous header learns its collision point. Called after the header measures.
  @Output() readonly layout = new EventEmitter<ISymbioteEvent>();

  // The one folded state cell, mutated in place by reduceSticky. The DECISIONS — zero-swallow gate,
  // debounce delay, rebuild ranges — all live there; this component supplies only the Angular
  // lifecycle (inputs + manual change detection), the interpolation-node + listener wiring, the
  // debounce setTimeout, and the markForCheck re-render.
  private readonly state = createInitialStickyState();
  // The animated node driving the transform (RN's animatedTranslateY), replaced by the
  // rebuild-interpolation effect. When the scroll value is native, this interpolation runs on the UI
  // thread: the smooth pin.
  private animatedTranslateY: AnimatedInterpolation = new AnimatedValue(0).interpolate({
    inputRange: [-1, 0],
    outputRange: [0, 0],
  });
  // The current interpolation node + its listener id, held so the next rebuild detaches the old
  // listener (an engine call the reducer does not own) and ngOnDestroy cleans up.
  private interpolation: AnimatedInterpolation | undefined;
  private debounceTimer: ReturnType<typeof setTimeout> | undefined;
  private listenerId: string | undefined;

  private readonly changeDetector = inject(ChangeDetectorRef);
  // This component's OWN host — the non-painting anchor `class="..."` at the use site resolves
  // onto (see anchorHostStyle's doc comment in primitives/shared.ts) — NOT the inner AnimatedView
  // one level down.
  private readonly elementRef = inject(ElementRef);

  ngOnInit(): void {
    this.dispatch({ kind: 'inputs-changed' });
  }

  // Rebuild on any layout/collision input change (RN's effect deps: measured, layoutY, layoutHeight,
  // scrollViewHeight, nextHeaderLayoutY, inverted). scrollAnimatedValue is stable for one ScrollView.
  ngOnChanges(): void {
    this.dispatch({ kind: 'inputs-changed' });
  }

  ngOnDestroy(): void {
    this.teardown();
  }

  get headerStyle(): unknown {
    // collapsable:false keeps the wrapper a real Yoga node; zIndex paints the pinned header OVER the
    // rows scrolling under it. The interpolation node rides inside the transform; AnimatedView's
    // reduceProps rasterizes it into a numeric translateY for the committed tree. This component is
    // its own ANCHOR_HOST_COMPONENTS entry, so a `class="..."` at its use site resolves onto
    // `elementRef`, not the inner AnimatedView — merge it back in (anchorHostStyle's doc comment),
    // anchor style first so the fixed transform/zIndex below still wins on conflict.
    return [
      anchorHostStyle(this.elementRef),
      { transform: [{ translateY: this.animatedTranslateY }], zIndex: STICKY_HEADER_Z_INDEX },
    ];
  }

  // Stable reference (bound once) so AnimatedView's directive does not re-wire the layout listener
  // every change-detection pass.
  private readonly onHostLayout = (event: ISymbioteEvent): void => this.handleLayout(event);

  // Also a stable reference, not a getter: jsonEqual (commit.ts) can't structurally compare the
  // embedded onLayout function, so a fresh object here would read as "props changed" on every
  // change-detection pass and force a real Fabric re-clone that cascades up every ancestor to the
  // root (see AnimatedComponentBase.reconcile()'s identical warning) — every unrelated press
  // anywhere in the app, not just this header's own layout events. Not `private`: the template
  // binds it directly (`strictTemplates` requires template-bound members stay accessible).
  readonly headerAnimatedProps: Record<string, unknown> = {
    onLayout: this.onHostLayout,
    collapsable: false,
  };

  // The EXPLICIT debounced translateY overrides the committed transform for hit-testing while
  // animatedTranslateY does the smooth (native-driven) pin (RN ScrollViewStickyHeader.js).
  get passthrough(): { style: { transform: Array<{ translateY: number }> } } | null {
    return this.state.translateY !== null
      ? { style: { transform: [{ translateY: this.state.translateY }] } }
      : null;
  }

  private inputs(): IStickyReducerInputs {
    return {
      os: Platform.OS,
      inverted: this.inverted,
      scrollViewHeight: this.scrollViewHeight,
      nextHeaderLayoutY: this.nextHeaderLayoutY,
    };
  }

  private dispatch(action: IStickyAction): void {
    this.runEffects(reduceSticky(this.state, action, this.inputs()).effects);
  }

  private runEffects(effects: IStickyEffect[]): void {
    for (const effect of effects) {
      switch (effect.kind) {
        case 'rebuild-interpolation': {
          // Detach the old listener, build a fresh interpolation onto the shared scroll value, and
          // wire the settled-value listener (symbiote is always Fabric; RN attaches it only there).
          if (this.interpolation !== undefined && this.listenerId !== undefined) {
            this.interpolation.removeListener(this.listenerId);
            this.listenerId = undefined;
          }
          const next = this.scrollAnimatedValue.interpolate({
            inputRange: effect.inputRange,
            outputRange: effect.outputRange,
          });
          this.listenerId = next.addListener(this.animatedValueListener);
          this.interpolation = next;
          this.animatedTranslateY = next;
          dlog(
            `Angular ScrollViewStickyHeader interpolation measured=${this.state.measured} y=${this.state.layoutY}`,
          );
          break;
        }
        case 'schedule-debounce':
          // The animated value updates several times per frame; debounce the settled value into the
          // committed transform so hit detection stays current (a Fabric issue, worse on Android).
          if (this.debounceTimer !== undefined) clearTimeout(this.debounceTimer);
          this.debounceTimer = setTimeout(() => {
            this.debounceTimer = undefined;
            this.dispatch({ kind: 'debounce-fired', value: effect.value });
          }, effect.delay);
          break;
        case 'apply-passthrough':
          this.changeDetector.markForCheck();
          break;
        case 'record-header-y':
          // The Angular header records through the `layout` EventEmitter (handleLayout below), the
          // public recorder contract; the reducer emits no index for it.
          break;
      }
    }
  }

  // Record own y/height, mark measured, rebuild the interpolation (all via the reducer), then fire
  // the parent's recorder (RN ScrollViewStickyHeader.js._onLayout order). The wrapped child keeps its
  // own onLayout binding (projected with its bindings intact), so unlike React/Vue we do not forward.
  private handleLayout(event: ISymbioteEvent): void {
    const y = readLayoutNumber(event, 'y');
    const height = readLayoutNumber(event, 'height');
    // Keep the previous value when a field is absent (RN sets state only on a defined read).
    this.dispatch({
      kind: 'layout',
      y: y ?? this.state.layoutY,
      height: height ?? this.state.layoutHeight,
    });
    this.layout.emit(event);
    this.changeDetector.markForCheck();
  }

  private readonly animatedValueListener = ({ value }: { value: number | string }): void => {
    if (typeof value === 'number') this.dispatch({ kind: 'animated-tick', value });
  };

  private teardown(): void {
    if (this.interpolation !== undefined && this.listenerId !== undefined) {
      this.interpolation.removeListener(this.listenerId);
      this.listenerId = undefined;
    }
    if (this.debounceTimer !== undefined) {
      clearTimeout(this.debounceTimer);
      this.debounceTimer = undefined;
    }
  }
}

// adapters/react/src/components/scroll-view/sticky-header.tsx
// Sticky headers: the JS layer RN implements in ScrollView.js / ScrollViewStickyHeader.js.
//
// VERDICT (source-based): RN does stickiness PURELY IN JS. ScrollView.js (render, ~line
// 1690) wraps each child whose index is in `stickyHeaderIndices` in a ScrollViewStickyHeader,
// fed by a single `_scrollAnimatedValue` an Animated.event drives from `onScroll`
// (ScrollView.js ~line 1095). The native Fabric scroll view does NOT honor the index array on
// its own. Forwarding `stickyHeaderIndices` to native is a silent no-op. So we replicate the
// JS layer: subscribe each flagged child to the scroll offset and translate it to stay pinned.
// The interpolation mirrors ScrollViewStickyHeader.js (non-inverted + inverted branches) and now
// lives, framework-agnostic, in @symbiote-native/components (computeStickyInterpolation); this
// file holds the React component shell, the layout state, and the child-wrapping.

import {
  Children,
  createElement,
  isValidElement,
  useCallback,
  useEffect,
  useReducer,
  useRef,
  useState,
  type ComponentType,
  type ReactElement,
  type ReactNode,
} from 'react';
import {
  AnimatedInterpolation,
  AnimatedValue,
  Platform,
  dlog,
  type ISymbioteEvent,
} from '@symbiote-native/engine';
import {
  createInitialStickyState,
  nextStickyHeaderY,
  readLayoutNumber,
  reduceSticky,
  STICKY_HEADER_Z_INDEX,
  type IStickyAction,
  type IStickyEffect,
  type IStickyHeaderProps,
  type IStickyHeaderState,
  type IStickyReducerInputs,
} from '@symbiote-native/components';
import { Animated } from '../../modules/animated';

// The props RN passes a sticky header wrapper (ScrollViewStickyHeader.js): the framework-agnostic
// fields (IStickyHeaderProps) plus the React children slot. A custom StickyHeaderComponent must
// accept the same shape.
export type IStickyHeaderComponentProps = IStickyHeaderProps & {
  children?: ReactNode;
};

export type IStickyHeaderComponentType = ComponentType<IStickyHeaderComponentProps>;

function readChildOnLayout(child: ReactElement): ((event: ISymbioteEvent) => void) | undefined {
  const childProps = child.props;
  if (typeof childProps !== 'object' || childProps === null) return undefined;
  const handler = Reflect.get(childProps, 'onLayout');
  return typeof handler === 'function' ? handler : undefined;
}

function firstChild(children: ReactNode): ReactElement | undefined {
  const first = Children.toArray(children)[0];
  return isValidElement(first) ? first : undefined;
}

// One sticky header. Measures its own y/height via onLayout, interpolates the shared scroll
// offset into a translateY that keeps it pinned to the top (or bottom, inverted) until the next
// header collides with it, and drives that translate through the native driver when available so
// the pin tracks scroll on the UI thread (no JS jitter). The DECISIONS — the zero-swallow gate, the
// debounce delay, the rebuild-on-input-change ranges — live in `reduceSticky`
// (@symbiote-native/components); this component supplies only the React lifecycle: the ONE folded
// state cell, the interpolation-node + listener wiring, the debounce setTimeout, and the re-render.
export const ScrollViewStickyHeader: IStickyHeaderComponentType = props => {
  const { inverted, scrollViewHeight, scrollAnimatedValue, nextHeaderLayoutY, children } = props;

  // The one folded state cell (RN's scattered useState/useRef collapsed into IStickyHeaderState),
  // mutated in place by reduceSticky. Lazily created once.
  const stateRef = useRef<IStickyHeaderState | null>(null);
  const state = (stateRef.current ??= createInitialStickyState());
  const [, forceRender] = useReducer((tick: number): number => tick + 1, 0);

  // The animated node that drives the transform (RN's animatedTranslateY), rebuilt by the
  // rebuild-interpolation effect. When the scroll value is native, this interpolation runs on the
  // UI thread: the smooth pin.
  const [animatedTranslateY, setAnimatedTranslateY] = useState<AnimatedInterpolation>(() =>
    scrollAnimatedValue.interpolate({ inputRange: [-1, 0], outputRange: [0, 0] }),
  );

  const debounceTimer = useRef<ReturnType<typeof setTimeout> | null>(null);
  // The current interpolation node + its settled-value listener id, held so the next rebuild can
  // detach the old listener (engine calls the reducer does NOT own) and unmount can clean up.
  const interpolationRef = useRef<AnimatedInterpolation | null>(null);
  const listenerIdRef = useRef<string | null>(null);

  const inputsRef = useRef<IStickyReducerInputs>({
    os: Platform.OS,
    inverted,
    scrollViewHeight,
    nextHeaderLayoutY,
  });
  inputsRef.current = { os: Platform.OS, inverted, scrollViewHeight, nextHeaderLayoutY };

  // dispatch reaches through a ref because the effect executors dispatch follow-up actions
  // (the listener -> animated-tick, the debounce timer -> debounce-fired).
  const dispatchRef = useRef<(action: IStickyAction) => void>(() => {});

  const runEffects = useCallback(
    (effects: IStickyEffect[]): void => {
      for (const effect of effects) {
        switch (effect.kind) {
          case 'rebuild-interpolation': {
            // Detach the old listener, build a fresh interpolation onto the shared scroll value, and
            // wire the settled-value listener (symbiote is always Fabric; RN attaches it only there).
            const previous = interpolationRef.current;
            if (previous !== null && listenerIdRef.current !== null) {
              previous.removeListener(listenerIdRef.current);
              listenerIdRef.current = null;
            }
            const next = scrollAnimatedValue.interpolate({
              inputRange: effect.inputRange,
              outputRange: effect.outputRange,
            });
            listenerIdRef.current = next.addListener(({ value }): void => {
              if (typeof value === 'number') dispatchRef.current({ kind: 'animated-tick', value });
            });
            interpolationRef.current = next;
            setAnimatedTranslateY(next);
            break;
          }
          case 'schedule-debounce': {
            // The animated value updates several times per frame; debounce the settled value into the
            // committed transform so hit detection stays current (a Fabric issue, worse on Android).
            if (debounceTimer.current !== null) clearTimeout(debounceTimer.current);
            debounceTimer.current = setTimeout(() => {
              debounceTimer.current = null;
              dispatchRef.current({ kind: 'debounce-fired', value: effect.value });
            }, effect.delay);
            break;
          }
          case 'apply-passthrough':
            forceRender();
            break;
          case 'record-header-y':
            // React records through the wrapper's onLayout closure (props.onLayout, below), which
            // honors the public IStickyHeaderProps contract; the reducer emits no index for it.
            break;
        }
      }
    },
    [scrollAnimatedValue],
  );

  const dispatch = useCallback(
    (action: IStickyAction): void => {
      const current = stateRef.current;
      if (current === null) return;
      runEffects(reduceSticky(current, action, inputsRef.current).effects);
    },
    [runEffects],
  );
  dispatchRef.current = dispatch;

  // Rebuild when the collision/viewport inputs change (RN effect deps minus the layout state, which
  // dispatches 'layout' itself); also does the initial identity build on mount.
  useEffect(() => {
    dispatchRef.current({ kind: 'inputs-changed' });
  }, [inverted, scrollViewHeight, nextHeaderLayoutY, scrollAnimatedValue]);

  // Detach the listener + clear the debounce on unmount.
  useEffect(
    () => (): void => {
      const previous = interpolationRef.current;
      if (previous !== null && listenerIdRef.current !== null)
        previous.removeListener(listenerIdRef.current);
      if (debounceTimer.current !== null) clearTimeout(debounceTimer.current);
    },
    [],
  );

  const onLayout = (event: ISymbioteEvent): void => {
    const y = readLayoutNumber(event, 'y');
    const height = readLayoutNumber(event, 'height');
    // Keep the previous value when a field is absent (RN sets state only on a defined read).
    dispatch({ kind: 'layout', y: y ?? state.layoutY, height: height ?? state.layoutHeight });
    props.onLayout(event);
    const child = firstChild(children);
    const childOnLayout = child === undefined ? undefined : readChildOnLayout(child);
    childOnLayout?.(event);
  };

  // The EXPLICIT debounced translateY overrides the committed transform for hit-testing, while
  // `animatedTranslateY` does the smooth (native-driven) pin, per RN ScrollViewStickyHeader.js.
  const passthroughAnimatedPropExplicitValues =
    state.translateY !== null ? { style: { transform: [{ translateY: state.translateY }] } } : null;

  // collapsable:false keeps the wrapper a real Yoga node; zIndex makes the pinned header paint
  // OVER the rows scrolling under it. `style` is `unknown` on Animated.View, so the interpolation
  // transform passes with no cast.
  return createElement(
    Animated.View,
    {
      style: { transform: [{ translateY: animatedTranslateY }], zIndex: STICKY_HEADER_Z_INDEX },
      onLayout,
      collapsable: false,
      passthroughAnimatedPropExplicitValues,
    },
    children,
  );
};
ScrollViewStickyHeader.displayName = 'ScrollViewStickyHeader';

// Wrap each child flagged by `stickyHeaderIndices` in the sticky header component, fed by the
// shared scroll AnimatedValue. Mirrors ScrollView.js's render-time children.map (~line 1690).
// Returns the children unchanged when no indices are flagged.
//
// Cross-talk plumbing (RN's _headerLayoutYs + _onStickyHeaderLayout, ScrollView.js:1115-1143):
// `headerLayoutYs` is a child-index→measured-y map the parent keeps; each header reports its own
// y through `onHeaderLayoutY` as it measures, and we feed every header the y of the NEXT flagged
// header (the collision point past which it scrolls off) by looking up its successor's index in
// `stickyHeaderIndices`. The LAST flagged header has no successor, so its `nextHeaderLayoutY`
// stays undefined and it sticks indefinitely (correct).
export function wrapStickyHeaders(
  children: ReactNode,
  stickyHeaderIndices: number[] | undefined,
  scrollAnimatedValue: AnimatedValue,
  invertStickyHeaders: boolean | undefined,
  scrollViewHeight: number | undefined,
  StickyHeaderComponent: IStickyHeaderComponentType | undefined,
  headerLayoutYs: ReadonlyMap<number, number>,
  onHeaderLayoutY: (index: number, y: number) => void,
): ReactNode {
  if (stickyHeaderIndices === undefined || stickyHeaderIndices.length === 0) return children;
  const Wrapper = StickyHeaderComponent ?? ScrollViewStickyHeader;
  return Children.toArray(children).map((child, index) => {
    const indexOfIndex = stickyHeaderIndices.indexOf(index);
    if (indexOfIndex === -1 || !isValidElement(child)) return child;
    // The next flagged header's measured y, by index order in stickyHeaderIndices (RN
    // ScrollView.js:1695 nextIndex). undefined until that header has measured (or for the last).
    const nextIndex = stickyHeaderIndices[indexOfIndex + 1];
    const nextHeaderLayoutY = nextStickyHeaderY(stickyHeaderIndices, indexOfIndex, headerLayoutYs);
    dlog(
      `ScrollView sticky-header wrap index=${index} next=${nextIndex} nextY=${nextHeaderLayoutY}`,
    );
    return createElement(
      Wrapper,
      {
        key: child.key ?? `sticky-${index}`,
        nextHeaderLayoutY,
        // RN _onStickyHeaderLayout: record this header's own y, then push it to the previous
        // header as its nextHeaderLayoutY. We record into the parent map; the lookup above feeds
        // it forward on the resulting re-render.
        onLayout: (event: ISymbioteEvent): void => {
          const y = readLayoutNumber(event, 'y');
          if (y !== undefined) onHeaderLayoutY(index, y);
        },
        scrollAnimatedValue,
        inverted: invertStickyHeaders,
        scrollViewHeight,
      },
      child,
    );
  });
}
