// examples/angular/src/screens/SensorsScreen.ts
import { Component, Injector, Signal, effect, inject, signal } from '@angular/core';
import { requireOptionalNativeModule } from 'expo-modules-core';
import { SafeAreaView, ScrollView, SymbioteHostPropsDirective, Text, View } from '@symbiote-native/angular';
import {
  AccelerometerService,
  DeviceMotionService,
  GyroscopeService,
  MagnetometerService,
  PedometerService,
  isAvailableAsync as isPedometerAvailableAsync,
  type IAccelerometerMeasurement,
  type IDeviceMotionMeasurement,
  type IGyroscopeMeasurement,
  type IMagnetometerMeasurement,
  type IPedometerResult,
} from '@symbiote-native/sensors/angular';
import { ROUTE_NAME } from '../routes';
import { LINE_COLOR, ROUTE_LINE_INFO } from '../navigation-lines';

// packages/sensors/src/angular/index.ts re-exports each *Service.connect() signal plus, for
// Pedometer only, the free isAvailableAsync() function — the DeviceSensor-based classes
// (Accelerometer/Gyroscope/Magnetometer/DeviceMotion) don't expose their own isAvailableAsync()
// through the Angular package barrel. So for those four, probe expo-modules-core's own
// requireOptionalNativeModule() directly, by the same native module name the wrapper itself
// resolves (packages/sensors/src/core/native/exponent-*.ts) — a real availability answer
// without reaching for an unexported symbol.
const NATIVE_MODULE_NAME = {
  Accelerometer: 'ExponentAccelerometer',
  Gyroscope: 'ExponentGyroscope',
  Magnetometer: 'ExponentMagnetometer',
  DeviceMotion: 'ExponentDeviceMotion',
} as const;

type INativeSensorProbe = {
  isAvailableAsync?: () => Promise<boolean>;
};

function probeNativeAvailability(nativeModuleName: string): Promise<boolean> {
  const nativeModule = requireOptionalNativeModule<INativeSensorProbe>(nativeModuleName);
  if (!nativeModule?.isAvailableAsync) {
    return Promise.resolve(false);
  }
  return nativeModule.isAvailableAsync();
}

// 4 distinct render states, never collapsed into each other (frontend-ux-best-practices'
// async-state rule) — "not available on this device" and "waiting for first reading" look
// identical from the JS side (a subscription to an unavailable sensor never throws, it just
// never fires) unless the availability check runs separately, which is exactly what this
// status signal does. Angular twin of ../../react/screens/SensorsScreen.tsx's ISensorStatus —
// same 4 states, same status-badge/reading-chip visual, React being this repo's "prove the
// pattern first" adapter for this package.
type ISensorCardStatus = 'checking' | 'unavailable' | 'waiting' | 'live';

const SENSOR_STATUS_TEXT: Record<ISensorCardStatus, string> = {
  checking: 'CHECKING…',
  unavailable: 'UNAVAILABLE',
  waiting: 'WAITING…',
  live: 'LIVE',
};

function sensorCardStatus<Measurement>(
  measurement: Signal<Measurement | null>,
  checkAvailability: () => Promise<boolean>,
  injector: Injector,
): Signal<ISensorCardStatus> {
  const status = signal<ISensorCardStatus>('checking');

  checkAvailability().then(available => {
    if (!available) {
      status.set('unavailable');
    } else if (status() === 'checking') {
      status.set('waiting');
    }
  });

  effect(
    () => {
      if (measurement() !== null && status() !== 'unavailable') {
        status.set('live');
      }
    },
    { injector },
  );

  return status.asReadonly();
}

// testID isn't a declared @Input() on View/Text (adapters/angular/src/primitives/shared.ts) — a
// bound [testID] fails NG8002 under examples/angular/tsconfig.angular.json's strictTemplates:
// true real ngc build, even though it works at runtime and under vitest's JIT compilation (see
// ../components/ResponderDemo.ts). Precomputed once per card, same as ResponderDemo's chip
// hostProps, rather than allocated fresh in the template on every change-detection pass.
function sensorCardHostProps(id: string): Record<string, unknown> {
  return { testID: `sensor-card-${id}` };
}

function sensorStatusHostProps(id: string): Record<string, unknown> {
  return { testID: `sensor-status-${id}` };
}

type IAxisReading = { x: number; y: number; z: number };

type IAxisSensorCard = {
  id: string;
  title: string;
  status: Signal<ISensorCardStatus>;
  reading: Signal<IAxisReading | null>;
  cardHostProps: Record<string, unknown>;
  statusHostProps: Record<string, unknown>;
};

/**
 * Sensors demo: one card per @symbiote-native/sensors sensor (Accelerometer, Gyroscope,
 * Magnetometer, DeviceMotion, Pedometer), each backed by its own Angular service's connect()
 * signal. iOS Simulator genuinely reports every CoreMotion/CMPedometer sensor as unavailable —
 * expected, not a bug (see packages/sensors/README.md's Notes section); a real device is
 * needed to see the "live" state. Angular twin of ../../react/screens/SensorsScreen.tsx — same
 * 4-state card (checking/unavailable/waiting/live) and X/Y/Z reading-chip layout, React being
 * this repo's "prove the pattern first" adapter for this package.
 */
@Component({
  selector: 'SensorsScreen',
  standalone: true,
  imports: [SafeAreaView, ScrollView, SymbioteHostPropsDirective, Text, View],
  template: `
    <SafeAreaView class="screen">
      <ScrollView testID="sensors-scroll" class="screen" contentContainerStyle="scroll-content">
        <View [class]="lineTagClass">
          <Text class="line-tag-text">{{ lineTagLabel }}</Text>
        </View>
        <View class="hero-card">
          <View class="hero-badge" [style]="heroBadgeStyle">
            <Text class="hero-badge-text">SN</Text>
          </View>
          <View class="hero-copy">
            <Text class="hero-title">Sensors</Text>
            <Text class="hero-body">
              @symbiote-native/sensors — live readings from five expo-sensors-backed hooks. A
              simulator reports every CoreMotion/CMPedometer-backed sensor as unavailable; a
              real device is needed to see live readings.
            </Text>
          </View>
        </View>

        @for (card of axisCards; track card.id) {
          <View [symbioteHostProps]="card.cardHostProps" class="sensor-card">
            <View class="sensor-card-header">
              <Text class="sensor-card-title">{{ card.title }}</Text>
              <View [symbioteHostProps]="card.statusHostProps" [class]="statusBadgeClass(card.status())">
                <Text class="sensor-status-text">{{ statusLabel(card.status()) }}</Text>
              </View>
            </View>
            @switch (card.status()) {
              @case ('checking') {
                <Text class="info-text">checking availability…</Text>
              }
              @case ('unavailable') {
                <Text class="info-text">not available on this device</Text>
              }
              @case ('waiting') {
                <Text class="info-text">waiting for first reading…</Text>
              }
              @case ('live') {
                @if (card.reading(); as reading) {
                  <View class="sensor-reading-row">
                    <View class="sensor-reading-chip">
                      <Text class="sensor-reading-label">X</Text>
                      <Text class="sensor-reading-value">{{ reading.x.toFixed(3) }}</Text>
                    </View>
                    <View class="sensor-reading-chip">
                      <Text class="sensor-reading-label">Y</Text>
                      <Text class="sensor-reading-value">{{ reading.y.toFixed(3) }}</Text>
                    </View>
                    <View class="sensor-reading-chip">
                      <Text class="sensor-reading-label">Z</Text>
                      <Text class="sensor-reading-value">{{ reading.z.toFixed(3) }}</Text>
                    </View>
                  </View>
                }
              }
            }
          </View>
        }

        <View testID="sensor-card-device-motion" class="sensor-card">
          <View class="sensor-card-header">
            <Text class="sensor-card-title">Device motion</Text>
            <View testID="sensor-status-device-motion" [class]="statusBadgeClass(deviceMotionStatus())">
              <Text class="sensor-status-text">{{ statusLabel(deviceMotionStatus()) }}</Text>
            </View>
          </View>
          @switch (deviceMotionStatus()) {
            @case ('checking') {
              <Text class="info-text">checking availability…</Text>
            }
            @case ('unavailable') {
              <Text class="info-text">not available on this device</Text>
            }
            @case ('waiting') {
              <Text class="info-text">waiting for first reading…</Text>
            }
            @case ('live') {
              @if (deviceMotion(); as motion) {
                <Text class="info-text">{{ 'interval: ' + motion.interval.toFixed(1) + 'ms' }}</Text>
                @if (motion.rotation; as rotation) {
                  <View class="sensor-reading-row">
                    <View class="sensor-reading-chip">
                      <Text class="sensor-reading-label">ALPHA</Text>
                      <Text class="sensor-reading-value">{{ rotation.alpha.toFixed(3) }}</Text>
                    </View>
                    <View class="sensor-reading-chip">
                      <Text class="sensor-reading-label">BETA</Text>
                      <Text class="sensor-reading-value">{{ rotation.beta.toFixed(3) }}</Text>
                    </View>
                    <View class="sensor-reading-chip">
                      <Text class="sensor-reading-label">GAMMA</Text>
                      <Text class="sensor-reading-value">{{ rotation.gamma.toFixed(3) }}</Text>
                    </View>
                  </View>
                }
              }
            }
          }
        </View>

        <View testID="sensor-card-pedometer" class="sensor-card">
          <View class="sensor-card-header">
            <Text class="sensor-card-title">Pedometer</Text>
            <View testID="sensor-status-pedometer" [class]="statusBadgeClass(pedometerStatus())">
              <Text class="sensor-status-text">{{ statusLabel(pedometerStatus()) }}</Text>
            </View>
          </View>
          @switch (pedometerStatus()) {
            @case ('checking') {
              <Text class="info-text">checking availability…</Text>
            }
            @case ('unavailable') {
              <Text class="info-text">not available on this device</Text>
            }
            @case ('waiting') {
              <Text class="info-text">waiting for first reading…</Text>
            }
            @case ('live') {
              @if (pedometer(); as steps) {
                <Text testID="sensors-pedometer-steps" class="sensor-reading-value">
                  {{ steps.steps + ' steps' }}
                </Text>
              }
            }
          }
        </View>
      </ScrollView>
    </SafeAreaView>
  `,
})
export class SensorsScreen {
  private readonly lineInfo = ROUTE_LINE_INFO[ROUTE_NAME.Sensors];
  readonly lineTagClass = `line-tag line-tag-${this.lineInfo.line}`;
  readonly lineTagLabel = `${this.lineInfo.code} · ${this.lineInfo.label}`;
  readonly heroBadgeStyle = { backgroundColor: LINE_COLOR.sensors };

  private readonly injector = inject(Injector);

  private readonly accelerometer: Signal<IAccelerometerMeasurement | null> = inject(AccelerometerService).connect();
  private readonly gyroscope: Signal<IGyroscopeMeasurement | null> = inject(GyroscopeService).connect();
  private readonly magnetometer: Signal<IMagnetometerMeasurement | null> = inject(MagnetometerService).connect();
  readonly deviceMotion: Signal<IDeviceMotionMeasurement | null> = inject(DeviceMotionService).connect();
  readonly pedometer: Signal<IPedometerResult | null> = inject(PedometerService).connect();

  readonly deviceMotionStatus = sensorCardStatus(
    this.deviceMotion,
    () => probeNativeAvailability(NATIVE_MODULE_NAME.DeviceMotion),
    this.injector,
  );
  readonly pedometerStatus = sensorCardStatus(this.pedometer, () => isPedometerAvailableAsync(), this.injector);

  readonly axisCards: IAxisSensorCard[] = [
    {
      id: 'accelerometer',
      title: 'Accelerometer',
      status: sensorCardStatus(
        this.accelerometer,
        () => probeNativeAvailability(NATIVE_MODULE_NAME.Accelerometer),
        this.injector,
      ),
      reading: this.accelerometer,
      cardHostProps: sensorCardHostProps('accelerometer'),
      statusHostProps: sensorStatusHostProps('accelerometer'),
    },
    {
      id: 'gyroscope',
      title: 'Gyroscope',
      status: sensorCardStatus(
        this.gyroscope,
        () => probeNativeAvailability(NATIVE_MODULE_NAME.Gyroscope),
        this.injector,
      ),
      reading: this.gyroscope,
      cardHostProps: sensorCardHostProps('gyroscope'),
      statusHostProps: sensorStatusHostProps('gyroscope'),
    },
    {
      id: 'magnetometer',
      title: 'Magnetometer',
      status: sensorCardStatus(
        this.magnetometer,
        () => probeNativeAvailability(NATIVE_MODULE_NAME.Magnetometer),
        this.injector,
      ),
      reading: this.magnetometer,
      cardHostProps: sensorCardHostProps('magnetometer'),
      statusHostProps: sensorStatusHostProps('magnetometer'),
    },
  ];

  statusBadgeClass(status: ISensorCardStatus): string {
    return `sensor-status-badge sensor-status-badge-${status}`;
  }

  statusLabel(status: ISensorCardStatus): string {
    return SENSOR_STATUS_TEXT[status];
  }
}

// examples/vue-sfc/screens/SensorsScreen.vue
<!--
  @symbiote-native/sensors tour stop — one card per DeviceSensor-shaped sensor (Accelerometer,
  Gyroscope, Magnetometer, DeviceMotion) plus Pedometer (free functions, no shared instance —
  see packages/sensors/src/core/pedometer.ts). Every composable comes straight from
  @symbiote-native/sensors/vue; the core singletons/free functions (imported from the package
  root) are used ONLY for their own isAvailableAsync() check, kept as a separate ref per sensor
  so "not available on this device" never gets conflated with "no reading yet" — both look
  identical on the iOS Simulator (no real CoreMotion/CMPedometer hardware), and only a distinct
  UI state tells them apart (see the symbiote-expo-native-module skill). Vue SFC twin of
  ../../react/screens/SensorsScreen.tsx — same 4-state card (checking/unavailable/waiting/live)
  and X/Y/Z reading-chip layout, React being this repo's "prove the pattern first" adapter for
  this package.
-->
<script setup lang="ts">
import { computed, onMounted, ref, type ComputedRef, type Ref } from 'vue';
import { SafeAreaView, ScrollView, Text, View } from '@symbiote-native/vue';
import {
  Accelerometer,
  Gyroscope,
  Magnetometer,
  DeviceMotion,
  isAvailableAsync as isPedometerAvailableAsync,
} from '@symbiote-native/sensors';
import {
  useAccelerometer,
  useGyroscope,
  useMagnetometer,
  useDeviceMotion,
  usePedometer,
} from '@symbiote-native/sensors/vue';
import { ROUTE_NAME } from '../routes';
import { LINE_COLOR, ROUTE_LINE_INFO } from '../navigation-lines';

const lineInfo = ROUTE_LINE_INFO[ROUTE_NAME.Sensors];

type ISensorAvailability = 'checking' | 'unavailable' | 'available';
type ISensorStatus = 'checking' | 'unavailable' | 'waiting' | 'live';

const SENSOR_STATUS_TEXT: Record<ISensorStatus, string> = {
  checking: 'CHECKING…',
  unavailable: 'UNAVAILABLE',
  waiting: 'WAITING…',
  live: 'LIVE',
};

// Wires one sensor's own isAvailableAsync() check into a local ref, on mount — kept separate
// from the composable's live-reading ref so "checking" / "not available" / "waiting for first
// reading" render as three genuinely distinct states, not one blank guess.
function useSensorAvailability(checkAsync: () => Promise<boolean>): Ref<ISensorAvailability> {
  const availability = ref<ISensorAvailability>('checking');
  onMounted(() => {
    void checkAsync().then(available => {
      availability.value = available ? 'available' : 'unavailable';
    });
  });
  return availability;
}

function sensorStatus(
  availability: Ref<ISensorAvailability>,
  hasReading: () => boolean,
): ComputedRef<ISensorStatus> {
  return computed(() => {
    if (availability.value === 'checking') return 'checking';
    if (availability.value === 'unavailable') return 'unavailable';
    return hasReading() ? 'live' : 'waiting';
  });
}

const accelerometer = useAccelerometer();
const accelerometerAvailability = useSensorAvailability(() => Accelerometer.isAvailableAsync());
const accelerometerStatus = sensorStatus(accelerometerAvailability, () => accelerometer.value !== null);

const gyroscope = useGyroscope();
const gyroscopeAvailability = useSensorAvailability(() => Gyroscope.isAvailableAsync());
const gyroscopeStatus = sensorStatus(gyroscopeAvailability, () => gyroscope.value !== null);

const magnetometer = useMagnetometer();
const magnetometerAvailability = useSensorAvailability(() => Magnetometer.isAvailableAsync());
const magnetometerStatus = sensorStatus(magnetometerAvailability, () => magnetometer.value !== null);

const deviceMotion = useDeviceMotion();
const deviceMotionAvailability = useSensorAvailability(() => DeviceMotion.isAvailableAsync());
const deviceMotionStatus = sensorStatus(deviceMotionAvailability, () => deviceMotion.value !== null);

const pedometer = usePedometer();
const pedometerAvailability = useSensorAvailability(() => isPedometerAvailableAsync());
const pedometerStatus = sensorStatus(pedometerAvailability, () => pedometer.value !== null);
</script>

<template>
  <SafeAreaView class="screen">
    <ScrollView testID="sensors-scroll" class="screen" content-container-style="scroll-content">
      <View :class="`line-tag line-tag-${lineInfo.line}`">
        <Text class="line-tag-text">{{ `${lineInfo.code} · ${lineInfo.label}` }}</Text>
      </View>
      <View class="hero-card">
        <View class="hero-badge" :style="{ backgroundColor: LINE_COLOR.sensors }">
          <Text class="hero-badge-text">{{ lineInfo.code }}</Text>
        </View>
        <View class="hero-copy">
          <Text class="hero-title">Sensors</Text>
          <Text class="hero-body"
            >@symbiote-native/sensors — live readings from five expo-sensors-backed hooks. A
            simulator reports every CoreMotion/CMPedometer-backed sensor as unavailable; a real
            device is needed to see live readings.</Text
          >
        </View>
      </View>

      <!-- Accelerometer -->
      <View testID="sensor-card-accelerometer" class="sensor-card">
        <View class="sensor-card-header">
          <Text class="sensor-card-title">Accelerometer</Text>
          <View :class="`sensor-status-badge sensor-status-badge-${accelerometerStatus}`">
            <Text class="sensor-status-text">{{ SENSOR_STATUS_TEXT[accelerometerStatus] }}</Text>
          </View>
        </View>
        <Text v-if="accelerometerStatus === 'checking'" class="info-text">checking availability…</Text>
        <Text v-else-if="accelerometerStatus === 'unavailable'" class="info-text"
          >not available on this device</Text
        >
        <Text v-else-if="accelerometerStatus === 'waiting'" class="info-text">waiting for first reading…</Text>
        <View v-else-if="accelerometer" class="sensor-reading-row">
          <View class="sensor-reading-chip">
            <Text class="sensor-reading-label">X</Text>
            <Text class="sensor-reading-value">{{ accelerometer.x.toFixed(3) }}</Text>
          </View>
          <View class="sensor-reading-chip">
            <Text class="sensor-reading-label">Y</Text>
            <Text class="sensor-reading-value">{{ accelerometer.y.toFixed(3) }}</Text>
          </View>
          <View class="sensor-reading-chip">
            <Text class="sensor-reading-label">Z</Text>
            <Text class="sensor-reading-value">{{ accelerometer.z.toFixed(3) }}</Text>
          </View>
        </View>
      </View>

      <!-- Gyroscope -->
      <View testID="sensor-card-gyroscope" class="sensor-card">
        <View class="sensor-card-header">
          <Text class="sensor-card-title">Gyroscope</Text>
          <View :class="`sensor-status-badge sensor-status-badge-${gyroscopeStatus}`">
            <Text class="sensor-status-text">{{ SENSOR_STATUS_TEXT[gyroscopeStatus] }}</Text>
          </View>
        </View>
        <Text v-if="gyroscopeStatus === 'checking'" class="info-text">checking availability…</Text>
        <Text v-else-if="gyroscopeStatus === 'unavailable'" class="info-text">not available on this device</Text>
        <Text v-else-if="gyroscopeStatus === 'waiting'" class="info-text">waiting for first reading…</Text>
        <View v-else-if="gyroscope" class="sensor-reading-row">
          <View class="sensor-reading-chip">
            <Text class="sensor-reading-label">X</Text>
            <Text class="sensor-reading-value">{{ gyroscope.x.toFixed(3) }}</Text>
          </View>
          <View class="sensor-reading-chip">
            <Text class="sensor-reading-label">Y</Text>
            <Text class="sensor-reading-value">{{ gyroscope.y.toFixed(3) }}</Text>
          </View>
          <View class="sensor-reading-chip">
            <Text class="sensor-reading-label">Z</Text>
            <Text class="sensor-reading-value">{{ gyroscope.z.toFixed(3) }}</Text>
          </View>
        </View>
      </View>

      <!-- Magnetometer -->
      <View testID="sensor-card-magnetometer" class="sensor-card">
        <View class="sensor-card-header">
          <Text class="sensor-card-title">Magnetometer</Text>
          <View :class="`sensor-status-badge sensor-status-badge-${magnetometerStatus}`">
            <Text class="sensor-status-text">{{ SENSOR_STATUS_TEXT[magnetometerStatus] }}</Text>
          </View>
        </View>
        <Text v-if="magnetometerStatus === 'checking'" class="info-text">checking availability…</Text>
        <Text v-else-if="magnetometerStatus === 'unavailable'" class="info-text"
          >not available on this device</Text
        >
        <Text v-else-if="magnetometerStatus === 'waiting'" class="info-text">waiting for first reading…</Text>
        <View v-else-if="magnetometer" class="sensor-reading-row">
          <View class="sensor-reading-chip">
            <Text class="sensor-reading-label">X</Text>
            <Text class="sensor-reading-value">{{ magnetometer.x.toFixed(3) }}</Text>
          </View>
          <View class="sensor-reading-chip">
            <Text class="sensor-reading-label">Y</Text>
            <Text class="sensor-reading-value">{{ magnetometer.y.toFixed(3) }}</Text>
          </View>
          <View class="sensor-reading-chip">
            <Text class="sensor-reading-label">Z</Text>
            <Text class="sensor-reading-value">{{ magnetometer.z.toFixed(3) }}</Text>
          </View>
        </View>
      </View>

      <!-- DeviceMotion — rotation is nested and can legitimately be absent from the very first
           event (the underlying sensor hasn't reported yet), so it's guarded at the field
           itself (deviceMotion?.rotation, not deviceMotion && deviceMotion.rotation — an
           unguarded nested read throws with no visible error and silently blanks the screen). -->
      <View testID="sensor-card-device-motion" class="sensor-card">
        <View class="sensor-card-header">
          <Text class="sensor-card-title">Device motion</Text>
          <View :class="`sensor-status-badge sensor-status-badge-${deviceMotionStatus}`">
            <Text class="sensor-status-text">{{ SENSOR_STATUS_TEXT[deviceMotionStatus] }}</Text>
          </View>
        </View>
        <Text v-if="deviceMotionStatus === 'checking'" class="info-text">checking availability…</Text>
        <Text v-else-if="deviceMotionStatus === 'unavailable'" class="info-text"
          >not available on this device</Text
        >
        <Text v-else-if="deviceMotionStatus === 'waiting'" class="info-text">waiting for first reading…</Text>
        <template v-else-if="deviceMotion">
          <Text class="info-text">{{ `interval: ${deviceMotion.interval.toFixed(1)}ms` }}</Text>
          <View v-if="deviceMotion.rotation" class="sensor-reading-row">
            <View class="sensor-reading-chip">
              <Text class="sensor-reading-label">ALPHA</Text>
              <Text class="sensor-reading-value">{{ deviceMotion.rotation.alpha.toFixed(3) }}</Text>
            </View>
            <View class="sensor-reading-chip">
              <Text class="sensor-reading-label">BETA</Text>
              <Text class="sensor-reading-value">{{ deviceMotion.rotation.beta.toFixed(3) }}</Text>
            </View>
            <View class="sensor-reading-chip">
              <Text class="sensor-reading-label">GAMMA</Text>
              <Text class="sensor-reading-value">{{ deviceMotion.rotation.gamma.toFixed(3) }}</Text>
            </View>
          </View>
        </template>
      </View>

      <!-- Pedometer — free functions, no shared instance, so both the availability check and
           the live subscription go through the standalone core exports instead of a singleton. -->
      <View testID="sensor-card-pedometer" class="sensor-card">
        <View class="sensor-card-header">
          <Text class="sensor-card-title">Pedometer</Text>
          <View :class="`sensor-status-badge sensor-status-badge-${pedometerStatus}`">
            <Text class="sensor-status-text">{{ SENSOR_STATUS_TEXT[pedometerStatus] }}</Text>
          </View>
        </View>
        <Text v-if="pedometerStatus === 'checking'" class="info-text">checking availability…</Text>
        <Text v-else-if="pedometerStatus === 'unavailable'" class="info-text">not available on this device</Text>
        <Text v-else-if="pedometerStatus === 'waiting'" class="info-text">waiting for first reading…</Text>
        <Text v-else-if="pedometer" testID="sensors-pedometer-steps" class="sensor-reading-value"
          >{{ `${pedometer.steps} steps` }}</Text
        >
      </View>
    </ScrollView>
  </SafeAreaView>
</template>
