// examples/react/screens/SensorsScreen.tsx
import { useEffect, useState } from 'react';
import type { ReactNode } from 'react';
import { SafeAreaView, ScrollView, Text, View } from '@symbiote-native/react';
import {
  Accelerometer,
  DeviceMotion,
  Gyroscope,
  Magnetometer,
  isAvailableAsync as isPedometerAvailableAsync,
} from '@symbiote-native/sensors';
import {
  useAccelerometer,
  useDeviceMotion,
  useGyroscope,
  useMagnetometer,
  usePedometer,
} from '@symbiote-native/sensors/react';
import { ROUTE_NAME } from '../routes';
import { LINE_COLOR, ROUTE_LINE_INFO } from '../navigation-lines';

// Pedometer has no shared singleton upstream (see packages/sensors' core/pedometer.ts) — wrapped
// in a stable module-level object so useSensorAvailability's effect dependency stays referentially
// constant across renders, same as the Accelerometer/Gyroscope/Magnetometer/DeviceMotion
// singletons it's rendered alongside below.
const PEDOMETER_SENSOR = { isAvailableAsync: isPedometerAvailableAsync };

type ISensorAvailability = 'checking' | 'available' | 'unavailable';
type ISensorStatus = 'checking' | 'unavailable' | 'waiting' | 'live';

const SENSOR_STATUS_TEXT: Record<ISensorStatus, string> = {
  checking: 'CHECKING…',
  unavailable: 'UNAVAILABLE',
  waiting: 'WAITING…',
  live: 'LIVE',
};

// isAvailableAsync() is a separate call from the live-reading hook — a sensor can be
// "unavailable" (iOS Simulator, every CoreMotion/CMPedometer-backed sensor) or "waiting for a
// first reading" (available, subscribed, native hasn't reported yet); rendering both as the same
// blank state would hide a real bug behind expected simulator behavior (see the
// symbiote-expo-native-module skill, and frontend-ux-best-practices's "render every async state").
function useSensorAvailability(sensor: { isAvailableAsync: () => Promise<boolean> }): ISensorAvailability {
  const [availability, setAvailability] = useState<ISensorAvailability>('checking');

  useEffect(() => {
    let isMounted = true;
    sensor.isAvailableAsync().then(isAvailable => {
      if (isMounted) {
        setAvailability(isAvailable ? 'available' : 'unavailable');
      }
    });
    return () => {
      isMounted = false;
    };
  }, [sensor]);

  return availability;
}

function resolveSensorStatus(availability: ISensorAvailability, hasReading: boolean): ISensorStatus {
  if (availability === 'checking') {
    return 'checking';
  }
  if (availability === 'unavailable') {
    return 'unavailable';
  }
  return hasReading ? 'live' : 'waiting';
}

function SensorStatusBadge({ status }: { status: ISensorStatus }) {
  return (
    <View className={`sensor-status-badge sensor-status-badge-${status}`}>
      <Text className="sensor-status-text">{SENSOR_STATUS_TEXT[status]}</Text>
    </View>
  );
}

function SensorCard({
  testID,
  title,
  status,
  children,
}: {
  testID: string;
  title: string;
  status: ISensorStatus;
  children?: ReactNode;
}) {
  return (
    <View testID={testID} className="sensor-card">
      <View className="sensor-card-header">
        <Text className="sensor-card-title">{title}</Text>
        <SensorStatusBadge status={status} />
      </View>
      {status === 'checking' && <Text className="info-text">checking availability…</Text>}
      {status === 'unavailable' && <Text className="info-text">not available on this device</Text>}
      {status === 'waiting' && <Text className="info-text">waiting for first reading…</Text>}
      {status === 'live' && children}
    </View>
  );
}

function AxisReadingRow({ measurement }: { measurement: { x: number; y: number; z: number } }) {
  return (
    <View className="sensor-reading-row">
      <View className="sensor-reading-chip">
        <Text className="sensor-reading-label">X</Text>
        <Text className="sensor-reading-value">{measurement.x.toFixed(3)}</Text>
      </View>
      <View className="sensor-reading-chip">
        <Text className="sensor-reading-label">Y</Text>
        <Text className="sensor-reading-value">{measurement.y.toFixed(3)}</Text>
      </View>
      <View className="sensor-reading-chip">
        <Text className="sensor-reading-label">Z</Text>
        <Text className="sensor-reading-value">{measurement.z.toFixed(3)}</Text>
      </View>
    </View>
  );
}

/**
 * @symbiote-native/sensors canary demo: one card per hook — Accelerometer, Gyroscope,
 * Magnetometer, DeviceMotion, Pedometer — each rendering its own checking/unavailable/waiting/
 * live state distinctly (SensorCard above), never conflating "still checking" with "no reading
 * yet" or "not available on this device". The iOS Simulator genuinely reports every
 * CoreMotion/CMPedometer-backed sensor as unavailable — expected, not a wiring bug.
 *
 * DeviceMotion's nested `rotation` field is guarded at the field itself
 * (`deviceMotion?.rotation && …`), not just at the top-level `deviceMotion` object — the
 * underlying native sensor can report its first event before `rotation` is populated, and an
 * unguarded nested read throws with no visible error anywhere (no redbox, no logcat), silently
 * blanking the screen instead.
 */
export function SensorsScreen() {
  const lineInfo = ROUTE_LINE_INFO[ROUTE_NAME.Sensors];

  const accelerometer = useAccelerometer();
  const accelerometerStatus = resolveSensorStatus(
    useSensorAvailability(Accelerometer),
    accelerometer !== null,
  );

  const gyroscope = useGyroscope();
  const gyroscopeStatus = resolveSensorStatus(useSensorAvailability(Gyroscope), gyroscope !== null);

  const magnetometer = useMagnetometer();
  const magnetometerStatus = resolveSensorStatus(
    useSensorAvailability(Magnetometer),
    magnetometer !== null,
  );

  const deviceMotion = useDeviceMotion();
  const deviceMotionStatus = resolveSensorStatus(
    useSensorAvailability(DeviceMotion),
    deviceMotion !== null,
  );

  const pedometer = usePedometer();
  const pedometerStatus = resolveSensorStatus(
    useSensorAvailability(PEDOMETER_SENSOR),
    pedometer !== null,
  );

  return (
    <SafeAreaView className="screen">
      <ScrollView testID="sensors-scroll" className="screen" contentContainerStyle="scroll-content">
        <View className={`line-tag line-tag-${lineInfo.line}`}>
          <Text className="line-tag-text">{`${lineInfo.code} · ${lineInfo.label}`}</Text>
        </View>
        <View className="hero-card">
          <View className="hero-badge" style={{ backgroundColor: LINE_COLOR.sensors }}>
            <Text className="hero-badge-text">{lineInfo.code}</Text>
          </View>
          <View className="hero-copy">
            <Text className="hero-title">Sensors</Text>
            <Text className="hero-body">
              @symbiote-native/sensors — live readings from five expo-sensors-backed hooks. A
              simulator reports every CoreMotion/CMPedometer-backed sensor as unavailable; a
              real device is needed to see live readings.
            </Text>
          </View>
        </View>

        <SensorCard testID="sensors-accelerometer" title="Accelerometer" status={accelerometerStatus}>
          {accelerometer && <AxisReadingRow measurement={accelerometer} />}
        </SensorCard>

        <SensorCard testID="sensors-gyroscope" title="Gyroscope" status={gyroscopeStatus}>
          {gyroscope && <AxisReadingRow measurement={gyroscope} />}
        </SensorCard>

        <SensorCard testID="sensors-magnetometer" title="Magnetometer" status={magnetometerStatus}>
          {magnetometer && <AxisReadingRow measurement={magnetometer} />}
        </SensorCard>

        <SensorCard testID="sensors-device-motion" title="Device motion" status={deviceMotionStatus}>
          {deviceMotion && (
            <Text className="info-text">{`interval: ${deviceMotion.interval.toFixed(1)}ms`}</Text>
          )}
          {deviceMotion?.rotation && (
            <View className="sensor-reading-row">
              <View className="sensor-reading-chip">
                <Text className="sensor-reading-label">ALPHA</Text>
                <Text className="sensor-reading-value">{deviceMotion.rotation.alpha.toFixed(3)}</Text>
              </View>
              <View className="sensor-reading-chip">
                <Text className="sensor-reading-label">BETA</Text>
                <Text className="sensor-reading-value">{deviceMotion.rotation.beta.toFixed(3)}</Text>
              </View>
              <View className="sensor-reading-chip">
                <Text className="sensor-reading-label">GAMMA</Text>
                <Text className="sensor-reading-value">{deviceMotion.rotation.gamma.toFixed(3)}</Text>
              </View>
            </View>
          )}
        </SensorCard>

        <SensorCard testID="sensors-pedometer" title="Pedometer" status={pedometerStatus}>
          {pedometer && (
            <Text testID="sensors-pedometer-steps" className="sensor-reading-value">
              {`${pedometer.steps} steps`}
            </Text>
          )}
        </SensorCard>
      </ScrollView>
    </SafeAreaView>
  );
}

// examples/vue-sfc/screens/SensorsScreen.vue
<!--
  @symbiote-native/sensors tour stop — one card per DeviceSensor-shaped sensor (Accelerometer,
  Gyroscope, Magnetometer, DeviceMotion) plus Pedometer (free functions, no shared instance —
  see packages/sensors/src/core/pedometer.ts). Every composable comes straight from
  @symbiote-native/sensors/vue; the core singletons/free functions (imported from the package
  root) are used ONLY for their own isAvailableAsync() check, kept as a separate ref per sensor
  so "not available on this device" never gets conflated with "no reading yet" — both look
  identical on the iOS Simulator (no real CoreMotion/CMPedometer hardware), and only a distinct
  UI state tells them apart (see the symbiote-expo-native-module skill). Vue SFC twin of
  ../../react/screens/SensorsScreen.tsx — same 4-state card (checking/unavailable/waiting/live)
  and X/Y/Z reading-chip layout, React being this repo's "prove the pattern first" adapter for
  this package.
-->
<script setup lang="ts">
import { computed, onMounted, ref, type ComputedRef, type Ref } from 'vue';
import { SafeAreaView, ScrollView, Text, View } from '@symbiote-native/vue';
import {
  Accelerometer,
  Gyroscope,
  Magnetometer,
  DeviceMotion,
  isAvailableAsync as isPedometerAvailableAsync,
} from '@symbiote-native/sensors';
import {
  useAccelerometer,
  useGyroscope,
  useMagnetometer,
  useDeviceMotion,
  usePedometer,
} from '@symbiote-native/sensors/vue';
import { ROUTE_NAME } from '../routes';
import { LINE_COLOR, ROUTE_LINE_INFO } from '../navigation-lines';

const lineInfo = ROUTE_LINE_INFO[ROUTE_NAME.Sensors];

type ISensorAvailability = 'checking' | 'unavailable' | 'available';
type ISensorStatus = 'checking' | 'unavailable' | 'waiting' | 'live';

const SENSOR_STATUS_TEXT: Record<ISensorStatus, string> = {
  checking: 'CHECKING…',
  unavailable: 'UNAVAILABLE',
  waiting: 'WAITING…',
  live: 'LIVE',
};

// Wires one sensor's own isAvailableAsync() check into a local ref, on mount — kept separate
// from the composable's live-reading ref so "checking" / "not available" / "waiting for first
// reading" render as three genuinely distinct states, not one blank guess.
function useSensorAvailability(checkAsync: () => Promise<boolean>): Ref<ISensorAvailability> {
  const availability = ref<ISensorAvailability>('checking');
  onMounted(() => {
    void checkAsync().then(available => {
      availability.value = available ? 'available' : 'unavailable';
    });
  });
  return availability;
}

function sensorStatus(
  availability: Ref<ISensorAvailability>,
  hasReading: () => boolean,
): ComputedRef<ISensorStatus> {
  return computed(() => {
    if (availability.value === 'checking') return 'checking';
    if (availability.value === 'unavailable') return 'unavailable';
    return hasReading() ? 'live' : 'waiting';
  });
}

const accelerometer = useAccelerometer();
const accelerometerAvailability = useSensorAvailability(() => Accelerometer.isAvailableAsync());
const accelerometerStatus = sensorStatus(accelerometerAvailability, () => accelerometer.value !== null);

const gyroscope = useGyroscope();
const gyroscopeAvailability = useSensorAvailability(() => Gyroscope.isAvailableAsync());
const gyroscopeStatus = sensorStatus(gyroscopeAvailability, () => gyroscope.value !== null);

const magnetometer = useMagnetometer();
const magnetometerAvailability = useSensorAvailability(() => Magnetometer.isAvailableAsync());
const magnetometerStatus = sensorStatus(magnetometerAvailability, () => magnetometer.value !== null);

const deviceMotion = useDeviceMotion();
const deviceMotionAvailability = useSensorAvailability(() => DeviceMotion.isAvailableAsync());
const deviceMotionStatus = sensorStatus(deviceMotionAvailability, () => deviceMotion.value !== null);

const pedometer = usePedometer();
const pedometerAvailability = useSensorAvailability(() => isPedometerAvailableAsync());
const pedometerStatus = sensorStatus(pedometerAvailability, () => pedometer.value !== null);
</script>

<template>
  <SafeAreaView class="screen">
    <ScrollView testID="sensors-scroll" class="screen" content-container-style="scroll-content">
      <View :class="`line-tag line-tag-${lineInfo.line}`">
        <Text class="line-tag-text">{{ `${lineInfo.code} · ${lineInfo.label}` }}</Text>
      </View>
      <View class="hero-card">
        <View class="hero-badge" :style="{ backgroundColor: LINE_COLOR.sensors }">
          <Text class="hero-badge-text">{{ lineInfo.code }}</Text>
        </View>
        <View class="hero-copy">
          <Text class="hero-title">Sensors</Text>
          <Text class="hero-body"
            >@symbiote-native/sensors — live readings from five expo-sensors-backed hooks. A
            simulator reports every CoreMotion/CMPedometer-backed sensor as unavailable; a real
            device is needed to see live readings.</Text
          >
        </View>
      </View>

      <!-- Accelerometer -->
      <View testID="sensor-card-accelerometer" class="sensor-card">
        <View class="sensor-card-header">
          <Text class="sensor-card-title">Accelerometer</Text>
          <View :class="`sensor-status-badge sensor-status-badge-${accelerometerStatus}`">
            <Text class="sensor-status-text">{{ SENSOR_STATUS_TEXT[accelerometerStatus] }}</Text>
          </View>
        </View>
        <Text v-if="accelerometerStatus === 'checking'" class="info-text">checking availability…</Text>
        <Text v-else-if="accelerometerStatus === 'unavailable'" class="info-text"
          >not available on this device</Text
        >
        <Text v-else-if="accelerometerStatus === 'waiting'" class="info-text">waiting for first reading…</Text>
        <View v-else-if="accelerometer" class="sensor-reading-row">
          <View class="sensor-reading-chip">
            <Text class="sensor-reading-label">X</Text>
            <Text class="sensor-reading-value">{{ accelerometer.x.toFixed(3) }}</Text>
          </View>
          <View class="sensor-reading-chip">
            <Text class="sensor-reading-label">Y</Text>
            <Text class="sensor-reading-value">{{ accelerometer.y.toFixed(3) }}</Text>
          </View>
          <View class="sensor-reading-chip">
            <Text class="sensor-reading-label">Z</Text>
            <Text class="sensor-reading-value">{{ accelerometer.z.toFixed(3) }}</Text>
          </View>
        </View>
      </View>

      <!-- Gyroscope -->
      <View testID="sensor-card-gyroscope" class="sensor-card">
        <View class="sensor-card-header">
          <Text class="sensor-card-title">Gyroscope</Text>
          <View :class="`sensor-status-badge sensor-status-badge-${gyroscopeStatus}`">
            <Text class="sensor-status-text">{{ SENSOR_STATUS_TEXT[gyroscopeStatus] }}</Text>
          </View>
        </View>
        <Text v-if="gyroscopeStatus === 'checking'" class="info-text">checking availability…</Text>
        <Text v-else-if="gyroscopeStatus === 'unavailable'" class="info-text">not available on this device</Text>
        <Text v-else-if="gyroscopeStatus === 'waiting'" class="info-text">waiting for first reading…</Text>
        <View v-else-if="gyroscope" class="sensor-reading-row">
          <View class="sensor-reading-chip">
            <Text class="sensor-reading-label">X</Text>
            <Text class="sensor-reading-value">{{ gyroscope.x.toFixed(3) }}</Text>
          </View>
          <View class="sensor-reading-chip">
            <Text class="sensor-reading-label">Y</Text>
            <Text class="sensor-reading-value">{{ gyroscope.y.toFixed(3) }}</Text>
          </View>
          <View class="sensor-reading-chip">
            <Text class="sensor-reading-label">Z</Text>
            <Text class="sensor-reading-value">{{ gyroscope.z.toFixed(3) }}</Text>
          </View>
        </View>
      </View>

      <!-- Magnetometer -->
      <View testID="sensor-card-magnetometer" class="sensor-card">
        <View class="sensor-card-header">
          <Text class="sensor-card-title">Magnetometer</Text>
          <View :class="`sensor-status-badge sensor-status-badge-${magnetometerStatus}`">
            <Text class="sensor-status-text">{{ SENSOR_STATUS_TEXT[magnetometerStatus] }}</Text>
          </View>
        </View>
        <Text v-if="magnetometerStatus === 'checking'" class="info-text">checking availability…</Text>
        <Text v-else-if="magnetometerStatus === 'unavailable'" class="info-text"
          >not available on this device</Text
        >
        <Text v-else-if="magnetometerStatus === 'waiting'" class="info-text">waiting for first reading…</Text>
        <View v-else-if="magnetometer" class="sensor-reading-row">
          <View class="sensor-reading-chip">
            <Text class="sensor-reading-label">X</Text>
            <Text class="sensor-reading-value">{{ magnetometer.x.toFixed(3) }}</Text>
          </View>
          <View class="sensor-reading-chip">
            <Text class="sensor-reading-label">Y</Text>
            <Text class="sensor-reading-value">{{ magnetometer.y.toFixed(3) }}</Text>
          </View>
          <View class="sensor-reading-chip">
            <Text class="sensor-reading-label">Z</Text>
            <Text class="sensor-reading-value">{{ magnetometer.z.toFixed(3) }}</Text>
          </View>
        </View>
      </View>

      <!-- DeviceMotion — rotation is nested and can legitimately be absent from the very first
           event (the underlying sensor hasn't reported yet), so it's guarded at the field
           itself (deviceMotion?.rotation, not deviceMotion && deviceMotion.rotation — an
           unguarded nested read throws with no visible error and silently blanks the screen). -->
      <View testID="sensor-card-device-motion" class="sensor-card">
        <View class="sensor-card-header">
          <Text class="sensor-card-title">Device motion</Text>
          <View :class="`sensor-status-badge sensor-status-badge-${deviceMotionStatus}`">
            <Text class="sensor-status-text">{{ SENSOR_STATUS_TEXT[deviceMotionStatus] }}</Text>
          </View>
        </View>
        <Text v-if="deviceMotionStatus === 'checking'" class="info-text">checking availability…</Text>
        <Text v-else-if="deviceMotionStatus === 'unavailable'" class="info-text"
          >not available on this device</Text
        >
        <Text v-else-if="deviceMotionStatus === 'waiting'" class="info-text">waiting for first reading…</Text>
        <template v-else-if="deviceMotion">
          <Text class="info-text">{{ `interval: ${deviceMotion.interval.toFixed(1)}ms` }}</Text>
          <View v-if="deviceMotion.rotation" class="sensor-reading-row">
            <View class="sensor-reading-chip">
              <Text class="sensor-reading-label">ALPHA</Text>
              <Text class="sensor-reading-value">{{ deviceMotion.rotation.alpha.toFixed(3) }}</Text>
            </View>
            <View class="sensor-reading-chip">
              <Text class="sensor-reading-label">BETA</Text>
              <Text class="sensor-reading-value">{{ deviceMotion.rotation.beta.toFixed(3) }}</Text>
            </View>
            <View class="sensor-reading-chip">
              <Text class="sensor-reading-label">GAMMA</Text>
              <Text class="sensor-reading-value">{{ deviceMotion.rotation.gamma.toFixed(3) }}</Text>
            </View>
          </View>
        </template>
      </View>

      <!-- Pedometer — free functions, no shared instance, so both the availability check and
           the live subscription go through the standalone core exports instead of a singleton. -->
      <View testID="sensor-card-pedometer" class="sensor-card">
        <View class="sensor-card-header">
          <Text class="sensor-card-title">Pedometer</Text>
          <View :class="`sensor-status-badge sensor-status-badge-${pedometerStatus}`">
            <Text class="sensor-status-text">{{ SENSOR_STATUS_TEXT[pedometerStatus] }}</Text>
          </View>
        </View>
        <Text v-if="pedometerStatus === 'checking'" class="info-text">checking availability…</Text>
        <Text v-else-if="pedometerStatus === 'unavailable'" class="info-text">not available on this device</Text>
        <Text v-else-if="pedometerStatus === 'waiting'" class="info-text">waiting for first reading…</Text>
        <Text v-else-if="pedometer" testID="sensors-pedometer-steps" class="sensor-reading-value"
          >{{ `${pedometer.steps} steps` }}</Text
        >
      </View>
    </ScrollView>
  </SafeAreaView>
</template>
