// examples/angular/src/components/ResponderDemo.ts
import { Component } from '@angular/core';
import {
  SymbioteHostPropsDirective,
  Text,
  View,
  type ISymbioteEvent,
} from '@symbiote-native/angular';
// static look lives here, compiled at build time by @symbiote-native/css-parser
import './ResponderDemo.css';

const RESPONDER_CHIPS = [0, 1, 2, 3, 4];
// Horizontal travel (in the touch's page units: px on Android, pt on iOS, so the feel
// differs a little per platform) after which the strip steals the gesture from the chip.
const RESPONDER_STEAL_DX = 64;

function firstTouchX(event: ISymbioteEvent): number {
  const touches = event.nativeEvent.touches;
  if (!Array.isArray(touches) || touches.length === 0) return 0;
  const first: unknown = touches[0];
  if (typeof first === 'object' && first !== null && 'pageX' in first) {
    const pageX = first.pageX;
    return typeof pageX === 'number' ? pageX : 0;
  }
  return 0;
}

// One chip's responder handlers, pre-bound to its index and bundled into a single `hostProps` bag
// so the template never allocates a fresh closure per change-detection pass.
interface IChipHandlers {
  index: number;
  hostProps: Record<string, unknown>;
}

// View's own primitive host only declares `style` as a real Angular @Input() (see
// adapters/angular/src/primitives/shared.ts) — the responder-negotiation callbacks below are NOT
// declared Inputs, so a bound `[onFoo]="…"` on a bare View fails Angular's real strictTemplates
// build (NG8002, `examples/angular/tsconfig.angular.json` has `strictTemplates: true`) even though
// it works at runtime via the engine's generic prop router. The established fix (see
// adapters/angular/src/components/pressable/index.ts's `[symbioteHostProps]` usage) is to bundle
// such props into one object and bind it through `[symbioteHostProps]`, a REAL declared @Input.
@Component({
  selector: 'ResponderDemo',
  standalone: true,
  imports: [View, Text, SymbioteHostPropsDirective],
  template: `
    <View class="section-tight">
      <Text class="section-label"
        >Responder · drag a chip vs hand-off to the strip</Text
      >
      <Text testID="resp-status" class="info-text">{{ status }}</Text>
      <Text
        testID="resp-transfer"
        class="transfer-text"
        [style]="{ color: transfer ? '#f6ad55' : '#41506a' }"
        >{{ transfer || 'transfer: —' }}</Text
      >
      <View [symbioteHostProps]="stripHostProps" class="strip-box">
        <View
          class="row-tight"
          [style]="{ transform: [{ translateX: rowDx }] }"
        >
          @for (chip of chipHandlers; track chip.index) {
            <View
              [symbioteHostProps]="chip.hostProps"
              class="chip"
              [style]="{
                borderColor:
                  activeChip === chip.index ? '#dd0031' : 'transparent',
                transform: [
                  { translateX: activeChip === chip.index ? chipDx : 0 },
                ],
              }"
            >
              <Text class="chip-text">{{ chip.index }}</Text>
            </View>
          }
        </View>
      </View>
    </View>
  `,
})
export class ResponderDemo {
  activeChip: number | null = null;
  chipDx = 0;
  rowDx = 0;
  status = 'tap a chip · drag it to move · drag far → strip steals it';
  transfer = '';
  private startX = 0;
  private panStartX = 0;
  private grabbed: number | null = null;

  readonly chipHandlers: IChipHandlers[] = RESPONDER_CHIPS.map(index => {
    const onStartShouldSetResponder = (): boolean => true;
    const onResponderGrant = (event: ISymbioteEvent): void => {
      this.startX = firstTouchX(event);
      this.grabbed = index;
      this.activeChip = index;
      this.chipDx = 0;
      this.rowDx = 0;
      this.transfer = '';
      this.status = `chip ${index} grabbed`;
    };
    const onResponderMove = (event: ISymbioteEvent): void => {
      const dx = firstTouchX(event) - this.startX;
      this.chipDx = dx;
      this.status = `chip ${index} moving · dx=${Math.round(dx)}`;
    };
    const onResponderTerminationRequest = (): boolean => true;
    const onResponderTerminate = (): void => {
      this.chipDx = 0;
      this.activeChip = null;
    };
    const onResponderRelease = (): void => {
      this.chipDx = 0;
      this.activeChip = null;
      this.status = `chip ${index} released`;
    };
    return {
      index,
      hostProps: {
        // testID isn't a declared @Input() on View either, and unlike a static string literal
        // (testID="…"), a bracket-bound [testID] fails NG8002 the same way the responder props
        // do — so it rides in the same symbioteHostProps bag rather than its own binding.
        testID: `resp-chip-${index}`,
        onStartShouldSetResponder,
        onResponderGrant,
        onResponderMove,
        onResponderTerminationRequest,
        onResponderTerminate,
        onResponderRelease,
      },
    };
  });

  // Claims the gesture only once the finger has travelled past the threshold, stealing
  // it from whichever chip currently holds it, the transfer path.
  private readonly onStripMoveShouldSet = (event: ISymbioteEvent): boolean =>
    this.grabbed !== null &&
    Math.abs(firstTouchX(event) - this.startX) > RESPONDER_STEAL_DX;

  private readonly onStripGrant = (event: ISymbioteEvent): void => {
    this.transfer = `↯ strip stole the gesture from chip ${this.grabbed ?? '?'}`;
    this.activeChip = null;
    this.chipDx = 0;
    this.panStartX = firstTouchX(event);
    this.status = 'strip panning';
  };

  private readonly onStripMove = (event: ISymbioteEvent): void => {
    this.rowDx = firstTouchX(event) - this.panStartX;
  };

  private readonly onStripRelease = (): void => {
    this.rowDx = 0;
    this.status = 'strip released';
  };

  private readonly onStripTerminate = (): void => {
    this.rowDx = 0;
  };

  readonly stripHostProps = {
    // testID isn't a declared @Input() on View either — same symbioteHostProps bag as the
    // per-chip hostProps above.
    testID: 'resp-strip',
    onMoveShouldSetResponder: this.onStripMoveShouldSet,
    onResponderGrant: this.onStripGrant,
    onResponderMove: this.onStripMove,
    onResponderRelease: this.onStripRelease,
    onResponderTerminate: this.onStripTerminate,
  };
}

// examples/react/components/ResponderDemo.tsx
import { useRef, useState } from 'react';
import { View, Text } from '@symbiote-native/react';
import { firstTouchX } from './event-utils';

// Responder: the gesture capabilities exposed here, shown so the grabbed
// element is the one that moves. Each chip is its OWN responder: it grabs on touch
// start and drags ITSELF (onResponderMove translates that chip). Drag a chip past a
// threshold and the surrounding strip STEALS the gesture: its onMoveShouldSetResponder
// fires once the finger has travelled far enough, the chip yields (onResponder-
// TerminationRequest -> terminate, so it snaps back) and the strip pans the whole row.
// A small drag moves the digit; a big drag hands off to the strip: move-should-set and
// transfer, each visible (and the separate "transfer" line lights on the hand-off).
// DEBUG logcat shows "responder transferred ... -> ..." at that moment.
const RESPONDER_CHIPS = [0, 1, 2, 3, 4];
// Horizontal travel (in the touch's page units: px on Android, pt on iOS, so the feel
// differs a little per platform) after which the strip steals the gesture from the chip.
const RESPONDER_STEAL_DX = 64;

export function ResponderDemo() {
  const [activeChip, setActiveChip] = useState<number | null>(null);
  const [chipDx, setChipDx] = useState(0);
  const [rowDx, setRowDx] = useState(0);
  const [status, setStatus] = useState(
    'tap a chip · drag it to move · drag far → strip steals it',
  );
  const [transfer, setTransfer] = useState('');
  const startX = useRef(0);
  const panStartX = useRef(0);
  const grabbed = useRef<number | null>(null);

  return (
    <View className="section-tight">
      <Text className="section-label">
        Responder · drag a chip vs hand-off to the strip
      </Text>
      <Text className="info-text">{status}</Text>
      {/* the separate transfer indicator, lit only when the strip steals the gesture */}
      <Text
        className="transfer-text"
        style={{ color: transfer ? '#f6ad55' : '#41506a' }}
      >
        {transfer || 'transfer: —'}
      </Text>
      <View
        // Claims the gesture only once the finger has travelled past the threshold,
        // stealing it from whichever chip currently holds it, the transfer path.
        onMoveShouldSetResponder={event =>
          grabbed.current !== null &&
          Math.abs(firstTouchX(event) - startX.current) > RESPONDER_STEAL_DX
        }
        onResponderGrant={event => {
          setTransfer(
            `↯ strip stole the gesture from chip ${grabbed.current ?? '?'}`,
          );
          setActiveChip(null);
          setChipDx(0);
          panStartX.current = firstTouchX(event);
          setStatus('strip panning');
        }}
        onResponderMove={event =>
          setRowDx(firstTouchX(event) - panStartX.current)
        }
        onResponderRelease={() => {
          setRowDx(0);
          setStatus('strip released');
        }}
        onResponderTerminate={() => setRowDx(0)}
        className="strip-box"
      >
        <View
          className="row-tight"
          style={{ transform: [{ translateX: rowDx }] }}
        >
          {RESPONDER_CHIPS.map(index => (
            <View
              key={index}
              testID={`resp-chip-${index}`}
              // Grabs on start and drags itself; yields to the strip past the threshold.
              onStartShouldSetResponder={() => true}
              onResponderGrant={event => {
                startX.current = firstTouchX(event);
                grabbed.current = index;
                setActiveChip(index);
                setChipDx(0);
                setRowDx(0);
                setTransfer('');
                setStatus(`chip ${index} grabbed`);
              }}
              onResponderMove={event => {
                const dx = firstTouchX(event) - startX.current;
                setChipDx(dx);
                setStatus(`chip ${index} moving · dx=${Math.round(dx)}`);
              }}
              onResponderTerminationRequest={() => true}
              onResponderTerminate={() => {
                setChipDx(0);
                setActiveChip(null);
              }}
              onResponderRelease={() => {
                setChipDx(0);
                setActiveChip(null);
                setStatus(`chip ${index} released`);
              }}
              className="chip"
              style={{
                borderColor: activeChip === index ? '#7fb5ff' : 'transparent',
                transform: [{ translateX: activeChip === index ? chipDx : 0 }],
              }}
            >
              <Text className="chip-text">{index}</Text>
            </View>
          ))}
        </View>
      </View>
    </View>
  );
}
