// adapters/angular/src/components/scroll-view/sticky-header.ts
// Sticky headers: the Angular twin of adapters/{react,vue}/src/components/scroll-view/
// sticky-header.{tsx,ts}, the JS layer RN implements in ScrollView.js / ScrollViewStickyHeader.js.
//
// Source-based: RN does stickiness PURELY IN JS. A single `_scrollAnimatedValue` an Animated.event
// drives from `onScroll` feeds each flagged header's translateY through an interpolation that pins
// it to the top (or bottom, inverted) until the next header collides with it. The native Fabric
// scroll view does NOT honor `stickyHeaderIndices` on its own. The load-bearing top/inverted
// interpolation math (computeStickyInterpolation) lives framework-agnostic in @symbiotejs/components
// (ADR 0024); this file holds the Angular component shell, the layout state, and the interpolation
// build, sharing the math verbatim with React/Vue. Angular supplies only the lifecycle (inputs +
// manual change detection instead of useState/useEffect or refs/watch).
//
// This is the public sticky-header WRAPPER for explicit composition. ScrollView also auto-wraps
// projected direct children named by stickyHeaderIndices through its projection bridge (see
// projection.ts), because Angular templates cannot map <ng-content> children directly; that auto
// path intentionally uses this built-in wrapper rather than dynamically instantiating arbitrary
// custom component classes.

import {
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  Component,
  ElementRef,
  EventEmitter,
  Input,
  Output,
  inject,
  type OnChanges,
  type OnDestroy,
  type OnInit,
} from '@angular/core';
import {
  type AnimatedInterpolation,
  AnimatedValue,
  Platform,
  dlog,
  type ISymbioteEvent,
} from '@symbiotejs/engine';
import {
  computeStickyInterpolation,
  readLayoutNumber,
  stickyDebounceMs,
  STICKY_HEADER_Z_INDEX,
  type IStickyHeaderProps,
} from '@symbiotejs/components';
import { AnimatedView } from '../../modules/animated';
import { anchorHostStyle } from '../../primitives';

// A custom sticky wrapper must accept the same shape the built-in does: the IStickyHeaderProps
// fields as inputs + the wrapped child via <ng-content>. Unlike React/Vue, Angular ScrollView cannot
// AOT-safely instantiate an arbitrary component Type while auto-projecting stickyHeaderIndices,
// because that renderer-level bridge only sees committed engine nodes, not a ViewContainerRef with
// Angular projectable nodes. This type remains public for explicit composition: compose your wrapper
// around <ScrollViewStickyHeader>/<symbiote-sticky-header> in the template when custom visuals are
// needed. Auto projection intentionally uses the built-in wrapper.
export type IStickyHeaderComponentType = unknown;

// One sticky header. Measures its own y/height via onLayout, interpolates the shared scroll offset
// into a translateY that keeps it pinned to the top (or bottom, inverted) until the next header
// collides with it, and drives that translate through the native driver when available so the pin
// tracks scroll on the UI thread (no JS jitter). Ported from ScrollViewStickyHeader.js, including
// the Fabric ShadowTree debounce path. The inputs (scrollAnimatedValue/nextHeaderLayoutY/…) never
// reach the host node: they configure the interpolation; only the resolved transform reaches
// AnimatedView (a scrollAnimatedValue on a host node would crash Android's folly::dynamic).
@Component({
  selector: 'ScrollViewStickyHeader, symbiote-sticky-header',
  standalone: true,
  imports: [AnimatedView],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <AnimatedView
      [style]="headerStyle"
      [animatedProps]="headerAnimatedProps"
      [passthroughAnimatedPropExplicitValues]="passthrough"
    >
      <ng-content></ng-content>
    </AnimatedView>
  `,
})
export class ScrollViewStickyHeader
  implements Omit<IStickyHeaderProps, 'onLayout'>, OnInit, OnChanges, OnDestroy
{
  // A fresh fallback AnimatedValue keeps the component working if the parent ever fails to supply
  // one (the wrap invariant); held by IDENTITY in a plain field (Angular does not proxy fields).
  @Input() scrollAnimatedValue: AnimatedValue = new AnimatedValue(0);
  @Input() nextHeaderLayoutY: number | undefined = undefined;
  @Input() inverted: boolean | undefined = undefined;
  @Input() scrollViewHeight: number | undefined = undefined;
  // The parent's layout recorder (RN _onStickyHeaderLayout): records this header's own y so the
  // previous header learns its collision point. Called after the header measures.
  @Output() readonly layout = new EventEmitter<ISymbioteEvent>();

  private measured = false;
  private layoutY = 0;
  private layoutHeight = 0;
  // The animated node driving the transform (RN's animatedTranslateY). When the scroll value is
  // native (attachStickyScroll), this interpolation runs on the UI thread: the smooth pin.
  private animatedTranslateY: AnimatedInterpolation = new AnimatedValue(0).interpolate({
    inputRange: [-1, 0],
    outputRange: [0, 0],
  });
  // The debounced EXPLICIT translateY pushed to the committed transform via the passthrough, so the
  // Fabric ShadowTree (hit-testing) knows the pinned position while the native driver animates.
  private translateY: number | null = null;
  private haveReceivedInitialZeroTranslateY = true;
  private debounceTimer: ReturnType<typeof setTimeout> | undefined;
  private listenerId: string | undefined;

  private readonly changeDetector = inject(ChangeDetectorRef);
  // This component's OWN host — the non-painting anchor `class="..."` at the use site resolves
  // onto (see anchorHostStyle's doc comment in primitives/shared.ts) — NOT the inner AnimatedView
  // one level down.
  private readonly elementRef = inject(ElementRef);

  ngOnInit(): void {
    this.animatedTranslateY = this.scrollAnimatedValue.interpolate({
      inputRange: [-1, 0],
      outputRange: [0, 0],
    });
    this.rebuildInterpolation();
  }

  // Rebuild on any layout/collision input change (RN's effect deps: measured, layoutY, layoutHeight,
  // scrollViewHeight, nextHeaderLayoutY, inverted). scrollAnimatedValue is stable for one ScrollView.
  ngOnChanges(): void {
    this.rebuildInterpolation();
  }

  ngOnDestroy(): void {
    this.teardownInterpolation();
  }

  get headerStyle(): unknown {
    // collapsable:false keeps the wrapper a real Yoga node; zIndex paints the pinned header OVER the
    // rows scrolling under it. The interpolation node rides inside the transform; AnimatedView's
    // reduceProps rasterizes it into a numeric translateY for the committed tree. This component is
    // its own ANCHOR_HOST_COMPONENTS entry, so a `class="..."` at its use site resolves onto
    // `elementRef`, not the inner AnimatedView — merge it back in (anchorHostStyle's doc comment),
    // anchor style first so the fixed transform/zIndex below still wins on conflict.
    return [
      anchorHostStyle(this.elementRef),
      { transform: [{ translateY: this.animatedTranslateY }], zIndex: STICKY_HEADER_Z_INDEX },
    ];
  }

  // Stable reference (bound once) so AnimatedView's directive does not re-wire the layout listener
  // every change-detection pass.
  private readonly onHostLayout = (event: ISymbioteEvent): void => this.handleLayout(event);

  // Also a stable reference, not a getter: jsonEqual (commit.ts) can't structurally compare the
  // embedded onLayout function, so a fresh object here would read as "props changed" on every
  // change-detection pass and force a real Fabric re-clone that cascades up every ancestor to the
  // root (see AnimatedComponentBase.reconcile()'s identical warning) — every unrelated press
  // anywhere in the app, not just this header's own layout events. Not `private`: the template
  // binds it directly (`strictTemplates` requires template-bound members stay accessible).
  readonly headerAnimatedProps: Record<string, unknown> = {
    onLayout: this.onHostLayout,
    collapsable: false,
  };

  // The EXPLICIT debounced translateY overrides the committed transform for hit-testing while
  // animatedTranslateY does the smooth (native-driven) pin (RN ScrollViewStickyHeader.js).
  get passthrough(): { style: { transform: Array<{ translateY: number }> } } | null {
    return this.translateY !== null
      ? { style: { transform: [{ translateY: this.translateY }] } }
      : null;
  }

  // Record own y/height, mark measured, rebuild the interpolation, then fire the parent's recorder
  // (RN ScrollViewStickyHeader.js._onLayout order). The wrapped child keeps its own onLayout binding
  // (it is projected with its bindings intact), so unlike React/Vue we do not forward to it here.
  private handleLayout(event: ISymbioteEvent): void {
    const y = readLayoutNumber(event, 'y');
    const height = readLayoutNumber(event, 'height');
    if (y !== undefined) this.layoutY = y;
    if (height !== undefined) this.layoutHeight = height;
    this.measured = true;
    this.rebuildInterpolation();
    this.layout.emit(event);
    this.changeDetector.markForCheck();
  }

  // The animated value updates several times per frame during scroll; debounce it and push the
  // settled value into the committed transform so hit detection stays current (a Fabric-only issue,
  // worse on Android). A freshly-rebuilt interpolation re-emits 0; swallow that first zero (RN).
  private readonly animatedValueListener = ({ value }: { value: number | string }): void => {
    if (typeof value !== 'number') return;
    if (value === 0 && !this.haveReceivedInitialZeroTranslateY) {
      this.haveReceivedInitialZeroTranslateY = true;
      return;
    }
    if (this.debounceTimer !== undefined) clearTimeout(this.debounceTimer);
    this.debounceTimer = setTimeout(() => {
      this.translateY = value;
      if (value !== 0) this.haveReceivedInitialZeroTranslateY = false;
      this.changeDetector.markForCheck();
    }, stickyDebounceMs(Platform.OS));
  };

  private rebuildInterpolation(): void {
    this.teardownInterpolation();
    const { inputRange, outputRange } = computeStickyInterpolation({
      measured: this.measured,
      inverted: this.inverted,
      scrollViewHeight: this.scrollViewHeight,
      layoutY: this.layoutY,
      layoutHeight: this.layoutHeight,
      nextHeaderLayoutY: this.nextHeaderLayoutY,
    });
    const interpolation = this.scrollAnimatedValue.interpolate({ inputRange, outputRange });
    // symbiote is always Fabric: listen to the settled value to keep the ShadowTree transform
    // current for hit-testing (RN attaches this listener only under Fabric).
    this.listenerId = interpolation.addListener(this.animatedValueListener);
    this.animatedTranslateY = interpolation;
    dlog(
      `Angular ScrollViewStickyHeader interpolation measured=${this.measured} y=${this.layoutY}`,
    );
  }

  private teardownInterpolation(): void {
    if (this.listenerId !== undefined) {
      this.animatedTranslateY.removeListener(this.listenerId);
      this.listenerId = undefined;
    }
    if (this.debounceTimer !== undefined) {
      clearTimeout(this.debounceTimer);
      this.debounceTimer = undefined;
    }
  }
}

// adapters/react/src/scroll-view/sticky-header.tsx
// Sticky headers: the JS layer RN implements in ScrollView.js / ScrollViewStickyHeader.js.
//
// VERDICT (source-based): RN does stickiness PURELY IN JS. ScrollView.js (render, ~line
// 1690) wraps each child whose index is in `stickyHeaderIndices` in a ScrollViewStickyHeader,
// fed by a single `_scrollAnimatedValue` an Animated.event drives from `onScroll`
// (ScrollView.js ~line 1095). The native Fabric scroll view does NOT honor the index array on
// its own. Forwarding `stickyHeaderIndices` to native is a silent no-op. So we replicate the
// JS layer: subscribe each flagged child to the scroll offset and translate it to stay pinned.
// The interpolation mirrors ScrollViewStickyHeader.js (non-inverted + inverted branches) and now
// lives, framework-agnostic, in @symbiote/components (computeStickyInterpolation, ADR 0024); this
// file holds the React component shell, the layout state, and the child-wrapping.

import {
  Children,
  createElement,
  isValidElement,
  useCallback,
  useEffect,
  useRef,
  useState,
  type ComponentType,
  type ReactElement,
  type ReactNode,
} from 'react';
import {
  AnimatedInterpolation,
  AnimatedValue,
  Platform,
  dlog,
  type ISymbioteEvent,
} from '@symbiote/engine';
import {
  computeStickyInterpolation,
  nextStickyHeaderY,
  readLayoutNumber,
  stickyDebounceMs,
  STICKY_HEADER_Z_INDEX,
  type IStickyHeaderProps,
} from '@symbiote/components';
import { Animated } from '../animated';

// The props RN passes a sticky header wrapper (ScrollViewStickyHeader.js): the framework-agnostic
// fields (IStickyHeaderProps) plus the React children slot. A custom StickyHeaderComponent must
// accept the same shape.
export type IStickyHeaderComponentProps = IStickyHeaderProps & {
  children?: ReactNode;
};

export type IStickyHeaderComponentType = ComponentType<IStickyHeaderComponentProps>;

function readChildOnLayout(child: ReactElement): ((event: ISymbioteEvent) => void) | undefined {
  const childProps = child.props;
  if (typeof childProps !== 'object' || childProps === null) return undefined;
  const handler = Reflect.get(childProps, 'onLayout');
  return typeof handler === 'function' ? handler : undefined;
}

function firstChild(children: ReactNode): ReactElement | undefined {
  const first = Children.toArray(children)[0];
  return isValidElement(first) ? first : undefined;
}

// One sticky header. Measures its own y/height via onLayout, interpolates the shared scroll
// offset into a translateY that keeps it pinned to the top (or bottom, inverted) until the next
// header collides with it, and drives that translate through the native driver when available so
// the pin tracks scroll on the UI thread (no JS jitter). Ported from
// ScrollViewStickyHeader.js, including the Fabric ShadowTree debounce path.
export const ScrollViewStickyHeader: IStickyHeaderComponentType = props => {
  const { inverted, scrollViewHeight, scrollAnimatedValue, nextHeaderLayoutY, children } = props;
  const [measured, setMeasured] = useState(false);
  const [layoutY, setLayoutY] = useState(0);
  const [layoutHeight, setLayoutHeight] = useState(0);
  // The animated node that drives the transform (RN's animatedTranslateY). When the scroll value
  // is native (attachNativeEvent), this interpolation runs on the UI thread: the smooth pin.
  const [animatedTranslateY, setAnimatedTranslateY] = useState<AnimatedInterpolation>(() =>
    scrollAnimatedValue.interpolate({ inputRange: [-1, 0], outputRange: [0, 0] }),
  );
  // The debounced EXPLICIT translateY pushed to the committed transform via
  // passthroughAnimatedPropExplicitValues, so the Fabric ShadowTree (hit-testing) knows the pinned
  // position while the native driver animates. null until the listener first fires.
  const [translateY, setTranslateY] = useState<number | null>(null);
  const haveReceivedInitialZeroTranslateY = useRef(true);
  const debounceTimer = useRef<number | null>(null);

  useEffect(() => {
    if (translateY !== 0 && translateY !== null) haveReceivedInitialZeroTranslateY.current = false;
  }, [translateY]);

  // The animated value updates several times per frame during scroll; debounce it and push the
  // settled value into the committed transform so hit detection stays current (RN: a Fabric-only
  // issue, symbiote is always Fabric, and worse on Android).
  const animatedValueListener = useCallback(({ value }: { value: number | string }): void => {
    if (typeof value !== 'number') return;
    const timeout = stickyDebounceMs(Platform.OS);
    // A freshly-rebuilt interpolation re-emits 0 to its listeners; swallow that first zero (RN).
    if (value === 0 && !haveReceivedInitialZeroTranslateY.current) {
      haveReceivedInitialZeroTranslateY.current = true;
      return;
    }
    if (debounceTimer.current !== null) clearTimeout(debounceTimer.current);
    debounceTimer.current = setTimeout(() => setTranslateY(value), timeout);
  }, []);

  useEffect(() => {
    const { inputRange, outputRange } = computeStickyInterpolation({
      measured,
      inverted,
      scrollViewHeight,
      layoutY,
      layoutHeight,
      nextHeaderLayoutY,
    });
    const newAnimatedTranslateY = scrollAnimatedValue.interpolate({ inputRange, outputRange });
    // symbiote is always Fabric: listen to the settled value to keep the ShadowTree transform
    // current for hit-testing (RN attaches this listener only under Fabric).
    const listenerId = newAnimatedTranslateY.addListener(animatedValueListener);
    setAnimatedTranslateY(newAnimatedTranslateY);
    return () => {
      newAnimatedTranslateY.removeListener(listenerId);
      if (debounceTimer.current !== null) clearTimeout(debounceTimer.current);
    };
  }, [
    measured,
    layoutY,
    layoutHeight,
    scrollViewHeight,
    nextHeaderLayoutY,
    inverted,
    scrollAnimatedValue,
    animatedValueListener,
  ]);

  const onLayout = (event: ISymbioteEvent): void => {
    const y = readLayoutNumber(event, 'y');
    const height = readLayoutNumber(event, 'height');
    if (y !== undefined) setLayoutY(y);
    if (height !== undefined) setLayoutHeight(height);
    setMeasured(true);
    props.onLayout(event);
    const child = firstChild(children);
    const childOnLayout = child === undefined ? undefined : readChildOnLayout(child);
    childOnLayout?.(event);
  };

  // The EXPLICIT debounced translateY overrides the committed transform for hit-testing, while
  // `animatedTranslateY` does the smooth (native-driven) pin, per RN ScrollViewStickyHeader.js.
  const passthroughAnimatedPropExplicitValues =
    translateY !== null ? { style: { transform: [{ translateY }] } } : null;

  // collapsable:false keeps the wrapper a real Yoga node; zIndex makes the pinned header paint
  // OVER the rows scrolling under it. `style` is `unknown` on Animated.View, so the interpolation
  // transform passes with no cast.
  return createElement(
    Animated.View,
    {
      style: { transform: [{ translateY: animatedTranslateY }], zIndex: STICKY_HEADER_Z_INDEX },
      onLayout,
      collapsable: false,
      passthroughAnimatedPropExplicitValues,
    },
    children,
  );
};
ScrollViewStickyHeader.displayName = 'ScrollViewStickyHeader';

// Wrap each child flagged by `stickyHeaderIndices` in the sticky header component, fed by the
// shared scroll AnimatedValue. Mirrors ScrollView.js's render-time children.map (~line 1690).
// Returns the children unchanged when no indices are flagged.
//
// Cross-talk plumbing (RN's _headerLayoutYs + _onStickyHeaderLayout, ScrollView.js:1115-1143):
// `headerLayoutYs` is a child-index→measured-y map the parent keeps; each header reports its own
// y through `onHeaderLayoutY` as it measures, and we feed every header the y of the NEXT flagged
// header (the collision point past which it scrolls off) by looking up its successor's index in
// `stickyHeaderIndices`. The LAST flagged header has no successor, so its `nextHeaderLayoutY`
// stays undefined and it sticks indefinitely (correct).
export function wrapStickyHeaders(
  children: ReactNode,
  stickyHeaderIndices: number[] | undefined,
  scrollAnimatedValue: AnimatedValue,
  invertStickyHeaders: boolean | undefined,
  scrollViewHeight: number | undefined,
  StickyHeaderComponent: IStickyHeaderComponentType | undefined,
  headerLayoutYs: ReadonlyMap<number, number>,
  onHeaderLayoutY: (index: number, y: number) => void,
): ReactNode {
  if (stickyHeaderIndices === undefined || stickyHeaderIndices.length === 0) return children;
  const Wrapper = StickyHeaderComponent ?? ScrollViewStickyHeader;
  return Children.toArray(children).map((child, index) => {
    const indexOfIndex = stickyHeaderIndices.indexOf(index);
    if (indexOfIndex === -1 || !isValidElement(child)) return child;
    // The next flagged header's measured y, by index order in stickyHeaderIndices (RN
    // ScrollView.js:1695 nextIndex). undefined until that header has measured (or for the last).
    const nextIndex = stickyHeaderIndices[indexOfIndex + 1];
    const nextHeaderLayoutY = nextStickyHeaderY(stickyHeaderIndices, indexOfIndex, headerLayoutYs);
    dlog(
      `ScrollView sticky-header wrap index=${index} next=${nextIndex} nextY=${nextHeaderLayoutY}`,
    );
    return createElement(
      Wrapper,
      {
        key: child.key ?? `sticky-${index}`,
        nextHeaderLayoutY,
        // RN _onStickyHeaderLayout: record this header's own y, then push it to the previous
        // header as its nextHeaderLayoutY. We record into the parent map; the lookup above feeds
        // it forward on the resulting re-render.
        onLayout: (event: ISymbioteEvent): void => {
          const y = readLayoutNumber(event, 'y');
          if (y !== undefined) onHeaderLayoutY(index, y);
        },
        scrollAnimatedValue,
        inverted: invertStickyHeaders,
        scrollViewHeight,
      },
      child,
    );
  });
}
